// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: internal/engine/grpc/proto/automation.proto

package enginepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// EvaluateRequest contains automation evaluation parameters.
type EvaluateRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Context           *ExecutionContext      `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	Event             *AutomationEvent       `protobuf:"bytes,2,opt,name=event,proto3" json:"event,omitempty"`
	Rules             []*AutomationRule      `protobuf:"bytes,3,rep,name=rules,proto3" json:"rules,omitempty"`
	AutomationContext *AutomationContext     `protobuf:"bytes,4,opt,name=automation_context,json=automationContext,proto3" json:"automation_context,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *EvaluateRequest) Reset() {
	*x = EvaluateRequest{}
	mi := &file_internal_engine_grpc_proto_automation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvaluateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvaluateRequest) ProtoMessage() {}

func (x *EvaluateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_engine_grpc_proto_automation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvaluateRequest.ProtoReflect.Descriptor instead.
func (*EvaluateRequest) Descriptor() ([]byte, []int) {
	return file_internal_engine_grpc_proto_automation_proto_rawDescGZIP(), []int{0}
}

func (x *EvaluateRequest) GetContext() *ExecutionContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *EvaluateRequest) GetEvent() *AutomationEvent {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *EvaluateRequest) GetRules() []*AutomationRule {
	if x != nil {
		return x.Rules
	}
	return nil
}

func (x *EvaluateRequest) GetAutomationContext() *AutomationContext {
	if x != nil {
		return x.AutomationContext
	}
	return nil
}

// AutomationEvent represents a triggering event.
type AutomationEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	EntityId      string                 `protobuf:"bytes,3,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	EntityType    string                 `protobuf:"bytes,4,opt,name=entity_type,json=entityType,proto3" json:"entity_type,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Data          *structpb.Struct       `protobuf:"bytes,6,opt,name=data,proto3" json:"data,omitempty"`
	PreviousState *structpb.Struct       `protobuf:"bytes,7,opt,name=previous_state,json=previousState,proto3" json:"previous_state,omitempty"`
	CurrentState  *structpb.Struct       `protobuf:"bytes,8,opt,name=current_state,json=currentState,proto3" json:"current_state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AutomationEvent) Reset() {
	*x = AutomationEvent{}
	mi := &file_internal_engine_grpc_proto_automation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AutomationEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AutomationEvent) ProtoMessage() {}

func (x *AutomationEvent) ProtoReflect() protoreflect.Message {
	mi := &file_internal_engine_grpc_proto_automation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AutomationEvent.ProtoReflect.Descriptor instead.
func (*AutomationEvent) Descriptor() ([]byte, []int) {
	return file_internal_engine_grpc_proto_automation_proto_rawDescGZIP(), []int{1}
}

func (x *AutomationEvent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AutomationEvent) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *AutomationEvent) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

func (x *AutomationEvent) GetEntityType() string {
	if x != nil {
		return x.EntityType
	}
	return ""
}

func (x *AutomationEvent) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *AutomationEvent) GetData() *structpb.Struct {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *AutomationEvent) GetPreviousState() *structpb.Struct {
	if x != nil {
		return x.PreviousState
	}
	return nil
}

func (x *AutomationEvent) GetCurrentState() *structpb.Struct {
	if x != nil {
		return x.CurrentState
	}
	return nil
}

// AutomationRule defines an automation rule.
type AutomationRule struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Enabled       bool                   `protobuf:"varint,4,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Trigger       *RuleTrigger           `protobuf:"bytes,5,opt,name=trigger,proto3" json:"trigger,omitempty"`
	Conditions    []*RuleCondition       `protobuf:"bytes,6,rep,name=conditions,proto3" json:"conditions,omitempty"`
	Actions       []*RuleAction          `protobuf:"bytes,7,rep,name=actions,proto3" json:"actions,omitempty"`
	Cooldown      *durationpb.Duration   `protobuf:"bytes,8,opt,name=cooldown,proto3" json:"cooldown,omitempty"`
	Priority      int32                  `protobuf:"varint,9,opt,name=priority,proto3" json:"priority,omitempty"`
	StopOnMatch   bool                   `protobuf:"varint,10,opt,name=stop_on_match,json=stopOnMatch,proto3" json:"stop_on_match,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AutomationRule) Reset() {
	*x = AutomationRule{}
	mi := &file_internal_engine_grpc_proto_automation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AutomationRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AutomationRule) ProtoMessage() {}

func (x *AutomationRule) ProtoReflect() protoreflect.Message {
	mi := &file_internal_engine_grpc_proto_automation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AutomationRule.ProtoReflect.Descriptor instead.
func (*AutomationRule) Descriptor() ([]byte, []int) {
	return file_internal_engine_grpc_proto_automation_proto_rawDescGZIP(), []int{2}
}

func (x *AutomationRule) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AutomationRule) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AutomationRule) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *AutomationRule) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *AutomationRule) GetTrigger() *RuleTrigger {
	if x != nil {
		return x.Trigger
	}
	return nil
}

func (x *AutomationRule) GetConditions() []*RuleCondition {
	if x != nil {
		return x.Conditions
	}
	return nil
}

func (x *AutomationRule) GetActions() []*RuleAction {
	if x != nil {
		return x.Actions
	}
	return nil
}

func (x *AutomationRule) GetCooldown() *durationpb.Duration {
	if x != nil {
		return x.Cooldown
	}
	return nil
}

func (x *AutomationRule) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *AutomationRule) GetStopOnMatch() bool {
	if x != nil {
		return x.StopOnMatch
	}
	return false
}

// RuleTrigger defines what triggers a rule.
type RuleTrigger struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	EventTypes    []string               `protobuf:"bytes,2,rep,name=event_types,json=eventTypes,proto3" json:"event_types,omitempty"`
	Schedule      string                 `protobuf:"bytes,3,opt,name=schedule,proto3" json:"schedule,omitempty"`
	StateField    string                 `protobuf:"bytes,4,opt,name=state_field,json=stateField,proto3" json:"state_field,omitempty"`
	FromValues    []*structpb.Value      `protobuf:"bytes,5,rep,name=from_values,json=fromValues,proto3" json:"from_values,omitempty"`
	ToValues      []*structpb.Value      `protobuf:"bytes,6,rep,name=to_values,json=toValues,proto3" json:"to_values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RuleTrigger) Reset() {
	*x = RuleTrigger{}
	mi := &file_internal_engine_grpc_proto_automation_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuleTrigger) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuleTrigger) ProtoMessage() {}

func (x *RuleTrigger) ProtoReflect() protoreflect.Message {
	mi := &file_internal_engine_grpc_proto_automation_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuleTrigger.ProtoReflect.Descriptor instead.
func (*RuleTrigger) Descriptor() ([]byte, []int) {
	return file_internal_engine_grpc_proto_automation_proto_rawDescGZIP(), []int{3}
}

func (x *RuleTrigger) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *RuleTrigger) GetEventTypes() []string {
	if x != nil {
		return x.EventTypes
	}
	return nil
}

func (x *RuleTrigger) GetSchedule() string {
	if x != nil {
		return x.Schedule
	}
	return ""
}

func (x *RuleTrigger) GetStateField() string {
	if x != nil {
		return x.StateField
	}
	return ""
}

func (x *RuleTrigger) GetFromValues() []*structpb.Value {
	if x != nil {
		return x.FromValues
	}
	return nil
}

func (x *RuleTrigger) GetToValues() []*structpb.Value {
	if x != nil {
		return x.ToValues
	}
	return nil
}

// RuleCondition is a condition for rule evaluation.
type RuleCondition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Field         string                 `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	Operator      string                 `protobuf:"bytes,2,opt,name=operator,proto3" json:"operator,omitempty"`
	Value         *structpb.Value        `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	Not           bool                   `protobuf:"varint,4,opt,name=not,proto3" json:"not,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RuleCondition) Reset() {
	*x = RuleCondition{}
	mi := &file_internal_engine_grpc_proto_automation_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuleCondition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuleCondition) ProtoMessage() {}

func (x *RuleCondition) ProtoReflect() protoreflect.Message {
	mi := &file_internal_engine_grpc_proto_automation_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuleCondition.ProtoReflect.Descriptor instead.
func (*RuleCondition) Descriptor() ([]byte, []int) {
	return file_internal_engine_grpc_proto_automation_proto_rawDescGZIP(), []int{4}
}

func (x *RuleCondition) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *RuleCondition) GetOperator() string {
	if x != nil {
		return x.Operator
	}
	return ""
}

func (x *RuleCondition) GetValue() *structpb.Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *RuleCondition) GetNot() bool {
	if x != nil {
		return x.Not
	}
	return false
}

// RuleAction defines an action to execute.
type RuleAction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Target        string                 `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	Parameters    *structpb.Struct       `protobuf:"bytes,3,opt,name=parameters,proto3" json:"parameters,omitempty"`
	Delay         *durationpb.Duration   `protobuf:"bytes,4,opt,name=delay,proto3" json:"delay,omitempty"`
	Condition     *RuleCondition         `protobuf:"bytes,5,opt,name=condition,proto3" json:"condition,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RuleAction) Reset() {
	*x = RuleAction{}
	mi := &file_internal_engine_grpc_proto_automation_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuleAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuleAction) ProtoMessage() {}

func (x *RuleAction) ProtoReflect() protoreflect.Message {
	mi := &file_internal_engine_grpc_proto_automation_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuleAction.ProtoReflect.Descriptor instead.
func (*RuleAction) Descriptor() ([]byte, []int) {
	return file_internal_engine_grpc_proto_automation_proto_rawDescGZIP(), []int{5}
}

func (x *RuleAction) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *RuleAction) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *RuleAction) GetParameters() *structpb.Struct {
	if x != nil {
		return x.Parameters
	}
	return nil
}

func (x *RuleAction) GetDelay() *durationpb.Duration {
	if x != nil {
		return x.Delay
	}
	return nil
}

func (x *RuleAction) GetCondition() *RuleCondition {
	if x != nil {
		return x.Condition
	}
	return nil
}

// AutomationContext provides evaluation context.
type AutomationContext struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Timezone      string                 `protobuf:"bytes,2,opt,name=timezone,proto3" json:"timezone,omitempty"`
	Now           *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=now,proto3" json:"now,omitempty"`
	Variables     *structpb.Struct       `protobuf:"bytes,4,opt,name=variables,proto3" json:"variables,omitempty"`
	RecentEvents  []*AutomationEvent     `protobuf:"bytes,5,rep,name=recent_events,json=recentEvents,proto3" json:"recent_events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AutomationContext) Reset() {
	*x = AutomationContext{}
	mi := &file_internal_engine_grpc_proto_automation_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AutomationContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AutomationContext) ProtoMessage() {}

func (x *AutomationContext) ProtoReflect() protoreflect.Message {
	mi := &file_internal_engine_grpc_proto_automation_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AutomationContext.ProtoReflect.Descriptor instead.
func (*AutomationContext) Descriptor() ([]byte, []int) {
	return file_internal_engine_grpc_proto_automation_proto_rawDescGZIP(), []int{6}
}

func (x *AutomationContext) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AutomationContext) GetTimezone() string {
	if x != nil {
		return x.Timezone
	}
	return ""
}

func (x *AutomationContext) GetNow() *timestamppb.Timestamp {
	if x != nil {
		return x.Now
	}
	return nil
}

func (x *AutomationContext) GetVariables() *structpb.Struct {
	if x != nil {
		return x.Variables
	}
	return nil
}

func (x *AutomationContext) GetRecentEvents() []*AutomationEvent {
	if x != nil {
		return x.RecentEvents
	}
	return nil
}

// EvaluateResponse contains evaluation results.
type EvaluateResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	TriggeredRules     []*TriggeredRule       `protobuf:"bytes,1,rep,name=triggered_rules,json=triggeredRules,proto3" json:"triggered_rules,omitempty"`
	PendingActions     []*PendingAction       `protobuf:"bytes,2,rep,name=pending_actions,json=pendingActions,proto3" json:"pending_actions,omitempty"`
	SkippedRules       []*SkippedRule         `protobuf:"bytes,3,rep,name=skipped_rules,json=skippedRules,proto3" json:"skipped_rules,omitempty"`
	EvaluationDuration *durationpb.Duration   `protobuf:"bytes,4,opt,name=evaluation_duration,json=evaluationDuration,proto3" json:"evaluation_duration,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *EvaluateResponse) Reset() {
	*x = EvaluateResponse{}
	mi := &file_internal_engine_grpc_proto_automation_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvaluateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvaluateResponse) ProtoMessage() {}

func (x *EvaluateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_engine_grpc_proto_automation_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvaluateResponse.ProtoReflect.Descriptor instead.
func (*EvaluateResponse) Descriptor() ([]byte, []int) {
	return file_internal_engine_grpc_proto_automation_proto_rawDescGZIP(), []int{7}
}

func (x *EvaluateResponse) GetTriggeredRules() []*TriggeredRule {
	if x != nil {
		return x.TriggeredRules
	}
	return nil
}

func (x *EvaluateResponse) GetPendingActions() []*PendingAction {
	if x != nil {
		return x.PendingActions
	}
	return nil
}

func (x *EvaluateResponse) GetSkippedRules() []*SkippedRule {
	if x != nil {
		return x.SkippedRules
	}
	return nil
}

func (x *EvaluateResponse) GetEvaluationDuration() *durationpb.Duration {
	if x != nil {
		return x.EvaluationDuration
	}
	return nil
}

// TriggeredRule represents a rule that matched.
type TriggeredRule struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	RuleId            string                 `protobuf:"bytes,1,opt,name=rule_id,json=ruleId,proto3" json:"rule_id,omitempty"`
	RuleName          string                 `protobuf:"bytes,2,opt,name=rule_name,json=ruleName,proto3" json:"rule_name,omitempty"`
	MatchedConditions []string               `protobuf:"bytes,3,rep,name=matched_conditions,json=matchedConditions,proto3" json:"matched_conditions,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *TriggeredRule) Reset() {
	*x = TriggeredRule{}
	mi := &file_internal_engine_grpc_proto_automation_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggeredRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggeredRule) ProtoMessage() {}

func (x *TriggeredRule) ProtoReflect() protoreflect.Message {
	mi := &file_internal_engine_grpc_proto_automation_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggeredRule.ProtoReflect.Descriptor instead.
func (*TriggeredRule) Descriptor() ([]byte, []int) {
	return file_internal_engine_grpc_proto_automation_proto_rawDescGZIP(), []int{8}
}

func (x *TriggeredRule) GetRuleId() string {
	if x != nil {
		return x.RuleId
	}
	return ""
}

func (x *TriggeredRule) GetRuleName() string {
	if x != nil {
		return x.RuleName
	}
	return ""
}

func (x *TriggeredRule) GetMatchedConditions() []string {
	if x != nil {
		return x.MatchedConditions
	}
	return nil
}

// PendingAction is an action to execute.
type PendingAction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	RuleId        string                 `protobuf:"bytes,2,opt,name=rule_id,json=ruleId,proto3" json:"rule_id,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Target        string                 `protobuf:"bytes,4,opt,name=target,proto3" json:"target,omitempty"`
	Parameters    *structpb.Struct       `protobuf:"bytes,5,opt,name=parameters,proto3" json:"parameters,omitempty"`
	ExecuteAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=execute_at,json=executeAt,proto3" json:"execute_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PendingAction) Reset() {
	*x = PendingAction{}
	mi := &file_internal_engine_grpc_proto_automation_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PendingAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PendingAction) ProtoMessage() {}

func (x *PendingAction) ProtoReflect() protoreflect.Message {
	mi := &file_internal_engine_grpc_proto_automation_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PendingAction.ProtoReflect.Descriptor instead.
func (*PendingAction) Descriptor() ([]byte, []int) {
	return file_internal_engine_grpc_proto_automation_proto_rawDescGZIP(), []int{9}
}

func (x *PendingAction) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PendingAction) GetRuleId() string {
	if x != nil {
		return x.RuleId
	}
	return ""
}

func (x *PendingAction) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *PendingAction) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *PendingAction) GetParameters() *structpb.Struct {
	if x != nil {
		return x.Parameters
	}
	return nil
}

func (x *PendingAction) GetExecuteAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExecuteAt
	}
	return nil
}

// SkippedRule represents a rule that didn't match.
type SkippedRule struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	RuleId          string                 `protobuf:"bytes,1,opt,name=rule_id,json=ruleId,proto3" json:"rule_id,omitempty"`
	RuleName        string                 `protobuf:"bytes,2,opt,name=rule_name,json=ruleName,proto3" json:"rule_name,omitempty"`
	Reason          string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	FailedCondition string                 `protobuf:"bytes,4,opt,name=failed_condition,json=failedCondition,proto3" json:"failed_condition,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SkippedRule) Reset() {
	*x = SkippedRule{}
	mi := &file_internal_engine_grpc_proto_automation_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SkippedRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SkippedRule) ProtoMessage() {}

func (x *SkippedRule) ProtoReflect() protoreflect.Message {
	mi := &file_internal_engine_grpc_proto_automation_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SkippedRule.ProtoReflect.Descriptor instead.
func (*SkippedRule) Descriptor() ([]byte, []int) {
	return file_internal_engine_grpc_proto_automation_proto_rawDescGZIP(), []int{10}
}

func (x *SkippedRule) GetRuleId() string {
	if x != nil {
		return x.RuleId
	}
	return ""
}

func (x *SkippedRule) GetRuleName() string {
	if x != nil {
		return x.RuleName
	}
	return ""
}

func (x *SkippedRule) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *SkippedRule) GetFailedCondition() string {
	if x != nil {
		return x.FailedCondition
	}
	return ""
}

// ValidateRuleRequest contains a rule to validate.
type ValidateRuleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Context       *ExecutionContext      `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	Rule          *AutomationRule        `protobuf:"bytes,2,opt,name=rule,proto3" json:"rule,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateRuleRequest) Reset() {
	*x = ValidateRuleRequest{}
	mi := &file_internal_engine_grpc_proto_automation_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateRuleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateRuleRequest) ProtoMessage() {}

func (x *ValidateRuleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_engine_grpc_proto_automation_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateRuleRequest.ProtoReflect.Descriptor instead.
func (*ValidateRuleRequest) Descriptor() ([]byte, []int) {
	return file_internal_engine_grpc_proto_automation_proto_rawDescGZIP(), []int{11}
}

func (x *ValidateRuleRequest) GetContext() *ExecutionContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *ValidateRuleRequest) GetRule() *AutomationRule {
	if x != nil {
		return x.Rule
	}
	return nil
}

// ValidateRuleResponse contains validation results.
type ValidateRuleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valid         bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	Errors        []string               `protobuf:"bytes,2,rep,name=errors,proto3" json:"errors,omitempty"`
	Warnings      []string               `protobuf:"bytes,3,rep,name=warnings,proto3" json:"warnings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateRuleResponse) Reset() {
	*x = ValidateRuleResponse{}
	mi := &file_internal_engine_grpc_proto_automation_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateRuleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateRuleResponse) ProtoMessage() {}

func (x *ValidateRuleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_engine_grpc_proto_automation_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateRuleResponse.ProtoReflect.Descriptor instead.
func (*ValidateRuleResponse) Descriptor() ([]byte, []int) {
	return file_internal_engine_grpc_proto_automation_proto_rawDescGZIP(), []int{12}
}

func (x *ValidateRuleResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *ValidateRuleResponse) GetErrors() []string {
	if x != nil {
		return x.Errors
	}
	return nil
}

func (x *ValidateRuleResponse) GetWarnings() []string {
	if x != nil {
		return x.Warnings
	}
	return nil
}

// GetTriggersRequest requests supported triggers.
type GetTriggersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Context       *ExecutionContext      `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTriggersRequest) Reset() {
	*x = GetTriggersRequest{}
	mi := &file_internal_engine_grpc_proto_automation_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTriggersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTriggersRequest) ProtoMessage() {}

func (x *GetTriggersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_engine_grpc_proto_automation_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTriggersRequest.ProtoReflect.Descriptor instead.
func (*GetTriggersRequest) Descriptor() ([]byte, []int) {
	return file_internal_engine_grpc_proto_automation_proto_rawDescGZIP(), []int{13}
}

func (x *GetTriggersRequest) GetContext() *ExecutionContext {
	if x != nil {
		return x.Context
	}
	return nil
}

// GetTriggersResponse contains supported triggers.
type GetTriggersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Triggers      []*TriggerDefinition   `protobuf:"bytes,1,rep,name=triggers,proto3" json:"triggers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTriggersResponse) Reset() {
	*x = GetTriggersResponse{}
	mi := &file_internal_engine_grpc_proto_automation_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTriggersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTriggersResponse) ProtoMessage() {}

func (x *GetTriggersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_engine_grpc_proto_automation_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTriggersResponse.ProtoReflect.Descriptor instead.
func (*GetTriggersResponse) Descriptor() ([]byte, []int) {
	return file_internal_engine_grpc_proto_automation_proto_rawDescGZIP(), []int{14}
}

func (x *GetTriggersResponse) GetTriggers() []*TriggerDefinition {
	if x != nil {
		return x.Triggers
	}
	return nil
}

// TriggerDefinition describes a supported trigger.
type TriggerDefinition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	EventTypes    []string               `protobuf:"bytes,4,rep,name=event_types,json=eventTypes,proto3" json:"event_types,omitempty"`
	Parameters    []*ParameterDefinition `protobuf:"bytes,5,rep,name=parameters,proto3" json:"parameters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TriggerDefinition) Reset() {
	*x = TriggerDefinition{}
	mi := &file_internal_engine_grpc_proto_automation_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerDefinition) ProtoMessage() {}

func (x *TriggerDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_internal_engine_grpc_proto_automation_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerDefinition.ProtoReflect.Descriptor instead.
func (*TriggerDefinition) Descriptor() ([]byte, []int) {
	return file_internal_engine_grpc_proto_automation_proto_rawDescGZIP(), []int{15}
}

func (x *TriggerDefinition) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *TriggerDefinition) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TriggerDefinition) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *TriggerDefinition) GetEventTypes() []string {
	if x != nil {
		return x.EventTypes
	}
	return nil
}

func (x *TriggerDefinition) GetParameters() []*ParameterDefinition {
	if x != nil {
		return x.Parameters
	}
	return nil
}

// GetActionsRequest requests supported actions.
type GetActionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Context       *ExecutionContext      `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetActionsRequest) Reset() {
	*x = GetActionsRequest{}
	mi := &file_internal_engine_grpc_proto_automation_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetActionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetActionsRequest) ProtoMessage() {}

func (x *GetActionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_engine_grpc_proto_automation_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetActionsRequest.ProtoReflect.Descriptor instead.
func (*GetActionsRequest) Descriptor() ([]byte, []int) {
	return file_internal_engine_grpc_proto_automation_proto_rawDescGZIP(), []int{16}
}

func (x *GetActionsRequest) GetContext() *ExecutionContext {
	if x != nil {
		return x.Context
	}
	return nil
}

// GetActionsResponse contains supported actions.
type GetActionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Actions       []*ActionDefinition    `protobuf:"bytes,1,rep,name=actions,proto3" json:"actions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetActionsResponse) Reset() {
	*x = GetActionsResponse{}
	mi := &file_internal_engine_grpc_proto_automation_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetActionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetActionsResponse) ProtoMessage() {}

func (x *GetActionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_engine_grpc_proto_automation_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetActionsResponse.ProtoReflect.Descriptor instead.
func (*GetActionsResponse) Descriptor() ([]byte, []int) {
	return file_internal_engine_grpc_proto_automation_proto_rawDescGZIP(), []int{17}
}

func (x *GetActionsResponse) GetActions() []*ActionDefinition {
	if x != nil {
		return x.Actions
	}
	return nil
}

// ActionDefinition describes a supported action.
type ActionDefinition struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Type                string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Name                string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description         string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Parameters          []*ParameterDefinition `protobuf:"bytes,4,rep,name=parameters,proto3" json:"parameters,omitempty"`
	RequiredPermissions []string               `protobuf:"bytes,5,rep,name=required_permissions,json=requiredPermissions,proto3" json:"required_permissions,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ActionDefinition) Reset() {
	*x = ActionDefinition{}
	mi := &file_internal_engine_grpc_proto_automation_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionDefinition) ProtoMessage() {}

func (x *ActionDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_internal_engine_grpc_proto_automation_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionDefinition.ProtoReflect.Descriptor instead.
func (*ActionDefinition) Descriptor() ([]byte, []int) {
	return file_internal_engine_grpc_proto_automation_proto_rawDescGZIP(), []int{18}
}

func (x *ActionDefinition) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ActionDefinition) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ActionDefinition) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ActionDefinition) GetParameters() []*ParameterDefinition {
	if x != nil {
		return x.Parameters
	}
	return nil
}

func (x *ActionDefinition) GetRequiredPermissions() []string {
	if x != nil {
		return x.RequiredPermissions
	}
	return nil
}

// ParameterDefinition describes an action/trigger parameter.
type ParameterDefinition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Required      bool                   `protobuf:"varint,3,opt,name=required,proto3" json:"required,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Default       *structpb.Value        `protobuf:"bytes,5,opt,name=default,proto3" json:"default,omitempty"`
	Enum          []*structpb.Value      `protobuf:"bytes,6,rep,name=enum,proto3" json:"enum,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParameterDefinition) Reset() {
	*x = ParameterDefinition{}
	mi := &file_internal_engine_grpc_proto_automation_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParameterDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParameterDefinition) ProtoMessage() {}

func (x *ParameterDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_internal_engine_grpc_proto_automation_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParameterDefinition.ProtoReflect.Descriptor instead.
func (*ParameterDefinition) Descriptor() ([]byte, []int) {
	return file_internal_engine_grpc_proto_automation_proto_rawDescGZIP(), []int{19}
}

func (x *ParameterDefinition) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ParameterDefinition) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ParameterDefinition) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

func (x *ParameterDefinition) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ParameterDefinition) GetDefault() *structpb.Value {
	if x != nil {
		return x.Default
	}
	return nil
}

func (x *ParameterDefinition) GetEnum() []*structpb.Value {
	if x != nil {
		return x.Enum
	}
	return nil
}

var File_internal_engine_grpc_proto_automation_proto protoreflect.FileDescriptor

const file_internal_engine_grpc_proto_automation_proto_rawDesc = "" +
	"\n" +
	"+internal/engine/grpc/proto/automation.proto\x12\x10orbita.engine.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/duration.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a'internal/engine/grpc/proto/engine.proto\"\x94\x02\n" +
	"\x0fEvaluateRequest\x12<\n" +
	"\acontext\x18\x01 \x01(\v2\".orbita.engine.v1.ExecutionContextR\acontext\x127\n" +
	"\x05event\x18\x02 \x01(\v2!.orbita.engine.v1.AutomationEventR\x05event\x126\n" +
	"\x05rules\x18\x03 \x03(\v2 .orbita.engine.v1.AutomationRuleR\x05rules\x12R\n" +
	"\x12automation_context\x18\x04 \x01(\v2#.orbita.engine.v1.AutomationContextR\x11automationContext\"\xd8\x02\n" +
	"\x0fAutomationEvent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x1b\n" +
	"\tentity_id\x18\x03 \x01(\tR\bentityId\x12\x1f\n" +
	"\ventity_type\x18\x04 \x01(\tR\n" +
	"entityType\x128\n" +
	"\ttimestamp\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12+\n" +
	"\x04data\x18\x06 \x01(\v2\x17.google.protobuf.StructR\x04data\x12>\n" +
	"\x0eprevious_state\x18\a \x01(\v2\x17.google.protobuf.StructR\rpreviousState\x12<\n" +
	"\rcurrent_state\x18\b \x01(\v2\x17.google.protobuf.StructR\fcurrentState\"\x99\x03\n" +
	"\x0eAutomationRule\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x18\n" +
	"\aenabled\x18\x04 \x01(\bR\aenabled\x127\n" +
	"\atrigger\x18\x05 \x01(\v2\x1d.orbita.engine.v1.RuleTriggerR\atrigger\x12?\n" +
	"\n" +
	"conditions\x18\x06 \x03(\v2\x1f.orbita.engine.v1.RuleConditionR\n" +
	"conditions\x126\n" +
	"\aactions\x18\a \x03(\v2\x1c.orbita.engine.v1.RuleActionR\aactions\x125\n" +
	"\bcooldown\x18\b \x01(\v2\x19.google.protobuf.DurationR\bcooldown\x12\x1a\n" +
	"\bpriority\x18\t \x01(\x05R\bpriority\x12\"\n" +
	"\rstop_on_match\x18\n" +
	" \x01(\bR\vstopOnMatch\"\xed\x01\n" +
	"\vRuleTrigger\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x1f\n" +
	"\vevent_types\x18\x02 \x03(\tR\n" +
	"eventTypes\x12\x1a\n" +
	"\bschedule\x18\x03 \x01(\tR\bschedule\x12\x1f\n" +
	"\vstate_field\x18\x04 \x01(\tR\n" +
	"stateField\x127\n" +
	"\vfrom_values\x18\x05 \x03(\v2\x16.google.protobuf.ValueR\n" +
	"fromValues\x123\n" +
	"\tto_values\x18\x06 \x03(\v2\x16.google.protobuf.ValueR\btoValues\"\x81\x01\n" +
	"\rRuleCondition\x12\x14\n" +
	"\x05field\x18\x01 \x01(\tR\x05field\x12\x1a\n" +
	"\boperator\x18\x02 \x01(\tR\boperator\x12,\n" +
	"\x05value\x18\x03 \x01(\v2\x16.google.protobuf.ValueR\x05value\x12\x10\n" +
	"\x03not\x18\x04 \x01(\bR\x03not\"\xe1\x01\n" +
	"\n" +
	"RuleAction\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x16\n" +
	"\x06target\x18\x02 \x01(\tR\x06target\x127\n" +
	"\n" +
	"parameters\x18\x03 \x01(\v2\x17.google.protobuf.StructR\n" +
	"parameters\x12/\n" +
	"\x05delay\x18\x04 \x01(\v2\x19.google.protobuf.DurationR\x05delay\x12=\n" +
	"\tcondition\x18\x05 \x01(\v2\x1f.orbita.engine.v1.RuleConditionR\tcondition\"\xf5\x01\n" +
	"\x11AutomationContext\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1a\n" +
	"\btimezone\x18\x02 \x01(\tR\btimezone\x12,\n" +
	"\x03now\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x03now\x125\n" +
	"\tvariables\x18\x04 \x01(\v2\x17.google.protobuf.StructR\tvariables\x12F\n" +
	"\rrecent_events\x18\x05 \x03(\v2!.orbita.engine.v1.AutomationEventR\frecentEvents\"\xb6\x02\n" +
	"\x10EvaluateResponse\x12H\n" +
	"\x0ftriggered_rules\x18\x01 \x03(\v2\x1f.orbita.engine.v1.TriggeredRuleR\x0etriggeredRules\x12H\n" +
	"\x0fpending_actions\x18\x02 \x03(\v2\x1f.orbita.engine.v1.PendingActionR\x0ependingActions\x12B\n" +
	"\rskipped_rules\x18\x03 \x03(\v2\x1d.orbita.engine.v1.SkippedRuleR\fskippedRules\x12J\n" +
	"\x13evaluation_duration\x18\x04 \x01(\v2\x19.google.protobuf.DurationR\x12evaluationDuration\"t\n" +
	"\rTriggeredRule\x12\x17\n" +
	"\arule_id\x18\x01 \x01(\tR\x06ruleId\x12\x1b\n" +
	"\trule_name\x18\x02 \x01(\tR\bruleName\x12-\n" +
	"\x12matched_conditions\x18\x03 \x03(\tR\x11matchedConditions\"\xd8\x01\n" +
	"\rPendingAction\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\arule_id\x18\x02 \x01(\tR\x06ruleId\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x16\n" +
	"\x06target\x18\x04 \x01(\tR\x06target\x127\n" +
	"\n" +
	"parameters\x18\x05 \x01(\v2\x17.google.protobuf.StructR\n" +
	"parameters\x129\n" +
	"\n" +
	"execute_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\texecuteAt\"\x86\x01\n" +
	"\vSkippedRule\x12\x17\n" +
	"\arule_id\x18\x01 \x01(\tR\x06ruleId\x12\x1b\n" +
	"\trule_name\x18\x02 \x01(\tR\bruleName\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\x12)\n" +
	"\x10failed_condition\x18\x04 \x01(\tR\x0ffailedCondition\"\x89\x01\n" +
	"\x13ValidateRuleRequest\x12<\n" +
	"\acontext\x18\x01 \x01(\v2\".orbita.engine.v1.ExecutionContextR\acontext\x124\n" +
	"\x04rule\x18\x02 \x01(\v2 .orbita.engine.v1.AutomationRuleR\x04rule\"`\n" +
	"\x14ValidateRuleResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12\x16\n" +
	"\x06errors\x18\x02 \x03(\tR\x06errors\x12\x1a\n" +
	"\bwarnings\x18\x03 \x03(\tR\bwarnings\"R\n" +
	"\x12GetTriggersRequest\x12<\n" +
	"\acontext\x18\x01 \x01(\v2\".orbita.engine.v1.ExecutionContextR\acontext\"V\n" +
	"\x13GetTriggersResponse\x12?\n" +
	"\btriggers\x18\x01 \x03(\v2#.orbita.engine.v1.TriggerDefinitionR\btriggers\"\xc5\x01\n" +
	"\x11TriggerDefinition\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1f\n" +
	"\vevent_types\x18\x04 \x03(\tR\n" +
	"eventTypes\x12E\n" +
	"\n" +
	"parameters\x18\x05 \x03(\v2%.orbita.engine.v1.ParameterDefinitionR\n" +
	"parameters\"Q\n" +
	"\x11GetActionsRequest\x12<\n" +
	"\acontext\x18\x01 \x01(\v2\".orbita.engine.v1.ExecutionContextR\acontext\"R\n" +
	"\x12GetActionsResponse\x12<\n" +
	"\aactions\x18\x01 \x03(\v2\".orbita.engine.v1.ActionDefinitionR\aactions\"\xd6\x01\n" +
	"\x10ActionDefinition\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12E\n" +
	"\n" +
	"parameters\x18\x04 \x03(\v2%.orbita.engine.v1.ParameterDefinitionR\n" +
	"parameters\x121\n" +
	"\x14required_permissions\x18\x05 \x03(\tR\x13requiredPermissions\"\xd9\x01\n" +
	"\x13ParameterDefinition\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x1a\n" +
	"\brequired\x18\x03 \x01(\bR\brequired\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x120\n" +
	"\adefault\x18\x05 \x01(\v2\x16.google.protobuf.ValueR\adefault\x12*\n" +
	"\x04enum\x18\x06 \x03(\v2\x16.google.protobuf.ValueR\x04enum2\x8b\x03\n" +
	"\x10AutomationEngine\x12Q\n" +
	"\bEvaluate\x12!.orbita.engine.v1.EvaluateRequest\x1a\".orbita.engine.v1.EvaluateResponse\x12]\n" +
	"\fValidateRule\x12%.orbita.engine.v1.ValidateRuleRequest\x1a&.orbita.engine.v1.ValidateRuleResponse\x12c\n" +
	"\x14GetSupportedTriggers\x12$.orbita.engine.v1.GetTriggersRequest\x1a%.orbita.engine.v1.GetTriggersResponse\x12`\n" +
	"\x13GetSupportedActions\x12#.orbita.engine.v1.GetActionsRequest\x1a$.orbita.engine.v1.GetActionsResponseBEZCgithub.com/felixgeelhaar/orbita/internal/engine/grpc/proto;enginepbb\x06proto3"

var (
	file_internal_engine_grpc_proto_automation_proto_rawDescOnce sync.Once
	file_internal_engine_grpc_proto_automation_proto_rawDescData []byte
)

func file_internal_engine_grpc_proto_automation_proto_rawDescGZIP() []byte {
	file_internal_engine_grpc_proto_automation_proto_rawDescOnce.Do(func() {
		file_internal_engine_grpc_proto_automation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_engine_grpc_proto_automation_proto_rawDesc), len(file_internal_engine_grpc_proto_automation_proto_rawDesc)))
	})
	return file_internal_engine_grpc_proto_automation_proto_rawDescData
}

var file_internal_engine_grpc_proto_automation_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_internal_engine_grpc_proto_automation_proto_goTypes = []any{
	(*EvaluateRequest)(nil),       // 0: orbita.engine.v1.EvaluateRequest
	(*AutomationEvent)(nil),       // 1: orbita.engine.v1.AutomationEvent
	(*AutomationRule)(nil),        // 2: orbita.engine.v1.AutomationRule
	(*RuleTrigger)(nil),           // 3: orbita.engine.v1.RuleTrigger
	(*RuleCondition)(nil),         // 4: orbita.engine.v1.RuleCondition
	(*RuleAction)(nil),            // 5: orbita.engine.v1.RuleAction
	(*AutomationContext)(nil),     // 6: orbita.engine.v1.AutomationContext
	(*EvaluateResponse)(nil),      // 7: orbita.engine.v1.EvaluateResponse
	(*TriggeredRule)(nil),         // 8: orbita.engine.v1.TriggeredRule
	(*PendingAction)(nil),         // 9: orbita.engine.v1.PendingAction
	(*SkippedRule)(nil),           // 10: orbita.engine.v1.SkippedRule
	(*ValidateRuleRequest)(nil),   // 11: orbita.engine.v1.ValidateRuleRequest
	(*ValidateRuleResponse)(nil),  // 12: orbita.engine.v1.ValidateRuleResponse
	(*GetTriggersRequest)(nil),    // 13: orbita.engine.v1.GetTriggersRequest
	(*GetTriggersResponse)(nil),   // 14: orbita.engine.v1.GetTriggersResponse
	(*TriggerDefinition)(nil),     // 15: orbita.engine.v1.TriggerDefinition
	(*GetActionsRequest)(nil),     // 16: orbita.engine.v1.GetActionsRequest
	(*GetActionsResponse)(nil),    // 17: orbita.engine.v1.GetActionsResponse
	(*ActionDefinition)(nil),      // 18: orbita.engine.v1.ActionDefinition
	(*ParameterDefinition)(nil),   // 19: orbita.engine.v1.ParameterDefinition
	(*ExecutionContext)(nil),      // 20: orbita.engine.v1.ExecutionContext
	(*timestamppb.Timestamp)(nil), // 21: google.protobuf.Timestamp
	(*structpb.Struct)(nil),       // 22: google.protobuf.Struct
	(*durationpb.Duration)(nil),   // 23: google.protobuf.Duration
	(*structpb.Value)(nil),        // 24: google.protobuf.Value
}
var file_internal_engine_grpc_proto_automation_proto_depIdxs = []int32{
	20, // 0: orbita.engine.v1.EvaluateRequest.context:type_name -> orbita.engine.v1.ExecutionContext
	1,  // 1: orbita.engine.v1.EvaluateRequest.event:type_name -> orbita.engine.v1.AutomationEvent
	2,  // 2: orbita.engine.v1.EvaluateRequest.rules:type_name -> orbita.engine.v1.AutomationRule
	6,  // 3: orbita.engine.v1.EvaluateRequest.automation_context:type_name -> orbita.engine.v1.AutomationContext
	21, // 4: orbita.engine.v1.AutomationEvent.timestamp:type_name -> google.protobuf.Timestamp
	22, // 5: orbita.engine.v1.AutomationEvent.data:type_name -> google.protobuf.Struct
	22, // 6: orbita.engine.v1.AutomationEvent.previous_state:type_name -> google.protobuf.Struct
	22, // 7: orbita.engine.v1.AutomationEvent.current_state:type_name -> google.protobuf.Struct
	3,  // 8: orbita.engine.v1.AutomationRule.trigger:type_name -> orbita.engine.v1.RuleTrigger
	4,  // 9: orbita.engine.v1.AutomationRule.conditions:type_name -> orbita.engine.v1.RuleCondition
	5,  // 10: orbita.engine.v1.AutomationRule.actions:type_name -> orbita.engine.v1.RuleAction
	23, // 11: orbita.engine.v1.AutomationRule.cooldown:type_name -> google.protobuf.Duration
	24, // 12: orbita.engine.v1.RuleTrigger.from_values:type_name -> google.protobuf.Value
	24, // 13: orbita.engine.v1.RuleTrigger.to_values:type_name -> google.protobuf.Value
	24, // 14: orbita.engine.v1.RuleCondition.value:type_name -> google.protobuf.Value
	22, // 15: orbita.engine.v1.RuleAction.parameters:type_name -> google.protobuf.Struct
	23, // 16: orbita.engine.v1.RuleAction.delay:type_name -> google.protobuf.Duration
	4,  // 17: orbita.engine.v1.RuleAction.condition:type_name -> orbita.engine.v1.RuleCondition
	21, // 18: orbita.engine.v1.AutomationContext.now:type_name -> google.protobuf.Timestamp
	22, // 19: orbita.engine.v1.AutomationContext.variables:type_name -> google.protobuf.Struct
	1,  // 20: orbita.engine.v1.AutomationContext.recent_events:type_name -> orbita.engine.v1.AutomationEvent
	8,  // 21: orbita.engine.v1.EvaluateResponse.triggered_rules:type_name -> orbita.engine.v1.TriggeredRule
	9,  // 22: orbita.engine.v1.EvaluateResponse.pending_actions:type_name -> orbita.engine.v1.PendingAction
	10, // 23: orbita.engine.v1.EvaluateResponse.skipped_rules:type_name -> orbita.engine.v1.SkippedRule
	23, // 24: orbita.engine.v1.EvaluateResponse.evaluation_duration:type_name -> google.protobuf.Duration
	22, // 25: orbita.engine.v1.PendingAction.parameters:type_name -> google.protobuf.Struct
	21, // 26: orbita.engine.v1.PendingAction.execute_at:type_name -> google.protobuf.Timestamp
	20, // 27: orbita.engine.v1.ValidateRuleRequest.context:type_name -> orbita.engine.v1.ExecutionContext
	2,  // 28: orbita.engine.v1.ValidateRuleRequest.rule:type_name -> orbita.engine.v1.AutomationRule
	20, // 29: orbita.engine.v1.GetTriggersRequest.context:type_name -> orbita.engine.v1.ExecutionContext
	15, // 30: orbita.engine.v1.GetTriggersResponse.triggers:type_name -> orbita.engine.v1.TriggerDefinition
	19, // 31: orbita.engine.v1.TriggerDefinition.parameters:type_name -> orbita.engine.v1.ParameterDefinition
	20, // 32: orbita.engine.v1.GetActionsRequest.context:type_name -> orbita.engine.v1.ExecutionContext
	18, // 33: orbita.engine.v1.GetActionsResponse.actions:type_name -> orbita.engine.v1.ActionDefinition
	19, // 34: orbita.engine.v1.ActionDefinition.parameters:type_name -> orbita.engine.v1.ParameterDefinition
	24, // 35: orbita.engine.v1.ParameterDefinition.default:type_name -> google.protobuf.Value
	24, // 36: orbita.engine.v1.ParameterDefinition.enum:type_name -> google.protobuf.Value
	0,  // 37: orbita.engine.v1.AutomationEngine.Evaluate:input_type -> orbita.engine.v1.EvaluateRequest
	11, // 38: orbita.engine.v1.AutomationEngine.ValidateRule:input_type -> orbita.engine.v1.ValidateRuleRequest
	13, // 39: orbita.engine.v1.AutomationEngine.GetSupportedTriggers:input_type -> orbita.engine.v1.GetTriggersRequest
	16, // 40: orbita.engine.v1.AutomationEngine.GetSupportedActions:input_type -> orbita.engine.v1.GetActionsRequest
	7,  // 41: orbita.engine.v1.AutomationEngine.Evaluate:output_type -> orbita.engine.v1.EvaluateResponse
	12, // 42: orbita.engine.v1.AutomationEngine.ValidateRule:output_type -> orbita.engine.v1.ValidateRuleResponse
	14, // 43: orbita.engine.v1.AutomationEngine.GetSupportedTriggers:output_type -> orbita.engine.v1.GetTriggersResponse
	17, // 44: orbita.engine.v1.AutomationEngine.GetSupportedActions:output_type -> orbita.engine.v1.GetActionsResponse
	41, // [41:45] is the sub-list for method output_type
	37, // [37:41] is the sub-list for method input_type
	37, // [37:37] is the sub-list for extension type_name
	37, // [37:37] is the sub-list for extension extendee
	0,  // [0:37] is the sub-list for field type_name
}

func init() { file_internal_engine_grpc_proto_automation_proto_init() }
func file_internal_engine_grpc_proto_automation_proto_init() {
	if File_internal_engine_grpc_proto_automation_proto != nil {
		return
	}
	file_internal_engine_grpc_proto_engine_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_engine_grpc_proto_automation_proto_rawDesc), len(file_internal_engine_grpc_proto_automation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_engine_grpc_proto_automation_proto_goTypes,
		DependencyIndexes: file_internal_engine_grpc_proto_automation_proto_depIdxs,
		MessageInfos:      file_internal_engine_grpc_proto_automation_proto_msgTypes,
	}.Build()
	File_internal_engine_grpc_proto_automation_proto = out.File
	file_internal_engine_grpc_proto_automation_proto_goTypes = nil
	file_internal_engine_grpc_proto_automation_proto_depIdxs = nil
}
