// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: internal/engine/grpc/proto/automation.proto

package enginepb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AutomationEngine_Evaluate_FullMethodName             = "/orbita.engine.v1.AutomationEngine/Evaluate"
	AutomationEngine_ValidateRule_FullMethodName         = "/orbita.engine.v1.AutomationEngine/ValidateRule"
	AutomationEngine_GetSupportedTriggers_FullMethodName = "/orbita.engine.v1.AutomationEngine/GetSupportedTriggers"
	AutomationEngine_GetSupportedActions_FullMethodName  = "/orbita.engine.v1.AutomationEngine/GetSupportedActions"
)

// AutomationEngineClient is the client API for AutomationEngine service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AutomationEngine provides automation capabilities.
type AutomationEngineClient interface {
	// Evaluate checks triggers and returns actions to execute.
	Evaluate(ctx context.Context, in *EvaluateRequest, opts ...grpc.CallOption) (*EvaluateResponse, error)
	// ValidateRule validates an automation rule.
	ValidateRule(ctx context.Context, in *ValidateRuleRequest, opts ...grpc.CallOption) (*ValidateRuleResponse, error)
	// GetSupportedTriggers returns supported triggers.
	GetSupportedTriggers(ctx context.Context, in *GetTriggersRequest, opts ...grpc.CallOption) (*GetTriggersResponse, error)
	// GetSupportedActions returns supported actions.
	GetSupportedActions(ctx context.Context, in *GetActionsRequest, opts ...grpc.CallOption) (*GetActionsResponse, error)
}

type automationEngineClient struct {
	cc grpc.ClientConnInterface
}

func NewAutomationEngineClient(cc grpc.ClientConnInterface) AutomationEngineClient {
	return &automationEngineClient{cc}
}

func (c *automationEngineClient) Evaluate(ctx context.Context, in *EvaluateRequest, opts ...grpc.CallOption) (*EvaluateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EvaluateResponse)
	err := c.cc.Invoke(ctx, AutomationEngine_Evaluate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *automationEngineClient) ValidateRule(ctx context.Context, in *ValidateRuleRequest, opts ...grpc.CallOption) (*ValidateRuleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidateRuleResponse)
	err := c.cc.Invoke(ctx, AutomationEngine_ValidateRule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *automationEngineClient) GetSupportedTriggers(ctx context.Context, in *GetTriggersRequest, opts ...grpc.CallOption) (*GetTriggersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTriggersResponse)
	err := c.cc.Invoke(ctx, AutomationEngine_GetSupportedTriggers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *automationEngineClient) GetSupportedActions(ctx context.Context, in *GetActionsRequest, opts ...grpc.CallOption) (*GetActionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetActionsResponse)
	err := c.cc.Invoke(ctx, AutomationEngine_GetSupportedActions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AutomationEngineServer is the server API for AutomationEngine service.
// All implementations must embed UnimplementedAutomationEngineServer
// for forward compatibility.
//
// AutomationEngine provides automation capabilities.
type AutomationEngineServer interface {
	// Evaluate checks triggers and returns actions to execute.
	Evaluate(context.Context, *EvaluateRequest) (*EvaluateResponse, error)
	// ValidateRule validates an automation rule.
	ValidateRule(context.Context, *ValidateRuleRequest) (*ValidateRuleResponse, error)
	// GetSupportedTriggers returns supported triggers.
	GetSupportedTriggers(context.Context, *GetTriggersRequest) (*GetTriggersResponse, error)
	// GetSupportedActions returns supported actions.
	GetSupportedActions(context.Context, *GetActionsRequest) (*GetActionsResponse, error)
	mustEmbedUnimplementedAutomationEngineServer()
}

// UnimplementedAutomationEngineServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAutomationEngineServer struct{}

func (UnimplementedAutomationEngineServer) Evaluate(context.Context, *EvaluateRequest) (*EvaluateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Evaluate not implemented")
}
func (UnimplementedAutomationEngineServer) ValidateRule(context.Context, *ValidateRuleRequest) (*ValidateRuleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ValidateRule not implemented")
}
func (UnimplementedAutomationEngineServer) GetSupportedTriggers(context.Context, *GetTriggersRequest) (*GetTriggersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSupportedTriggers not implemented")
}
func (UnimplementedAutomationEngineServer) GetSupportedActions(context.Context, *GetActionsRequest) (*GetActionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSupportedActions not implemented")
}
func (UnimplementedAutomationEngineServer) mustEmbedUnimplementedAutomationEngineServer() {}
func (UnimplementedAutomationEngineServer) testEmbeddedByValue()                          {}

// UnsafeAutomationEngineServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AutomationEngineServer will
// result in compilation errors.
type UnsafeAutomationEngineServer interface {
	mustEmbedUnimplementedAutomationEngineServer()
}

func RegisterAutomationEngineServer(s grpc.ServiceRegistrar, srv AutomationEngineServer) {
	// If the following call panics, it indicates UnimplementedAutomationEngineServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AutomationEngine_ServiceDesc, srv)
}

func _AutomationEngine_Evaluate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EvaluateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AutomationEngineServer).Evaluate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AutomationEngine_Evaluate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AutomationEngineServer).Evaluate(ctx, req.(*EvaluateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AutomationEngine_ValidateRule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateRuleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AutomationEngineServer).ValidateRule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AutomationEngine_ValidateRule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AutomationEngineServer).ValidateRule(ctx, req.(*ValidateRuleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AutomationEngine_GetSupportedTriggers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTriggersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AutomationEngineServer).GetSupportedTriggers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AutomationEngine_GetSupportedTriggers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AutomationEngineServer).GetSupportedTriggers(ctx, req.(*GetTriggersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AutomationEngine_GetSupportedActions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetActionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AutomationEngineServer).GetSupportedActions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AutomationEngine_GetSupportedActions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AutomationEngineServer).GetSupportedActions(ctx, req.(*GetActionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AutomationEngine_ServiceDesc is the grpc.ServiceDesc for AutomationEngine service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AutomationEngine_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "orbita.engine.v1.AutomationEngine",
	HandlerType: (*AutomationEngineServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Evaluate",
			Handler:    _AutomationEngine_Evaluate_Handler,
		},
		{
			MethodName: "ValidateRule",
			Handler:    _AutomationEngine_ValidateRule_Handler,
		},
		{
			MethodName: "GetSupportedTriggers",
			Handler:    _AutomationEngine_GetSupportedTriggers_Handler,
		},
		{
			MethodName: "GetSupportedActions",
			Handler:    _AutomationEngine_GetSupportedActions_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/engine/grpc/proto/automation.proto",
}
