// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: internal/engine/grpc/proto/classifier.proto

package enginepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ClassifyRequest contains content to classify.
type ClassifyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Context       *ExecutionContext      `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	Input         *ClassifyInput         `protobuf:"bytes,2,opt,name=input,proto3" json:"input,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClassifyRequest) Reset() {
	*x = ClassifyRequest{}
	mi := &file_internal_engine_grpc_proto_classifier_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClassifyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClassifyRequest) ProtoMessage() {}

func (x *ClassifyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_engine_grpc_proto_classifier_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClassifyRequest.ProtoReflect.Descriptor instead.
func (*ClassifyRequest) Descriptor() ([]byte, []int) {
	return file_internal_engine_grpc_proto_classifier_proto_rawDescGZIP(), []int{0}
}

func (x *ClassifyRequest) GetContext() *ExecutionContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *ClassifyRequest) GetInput() *ClassifyInput {
	if x != nil {
		return x.Input
	}
	return nil
}

// ClassifyInput contains the content to be classified.
type ClassifyInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Source        string                 `protobuf:"bytes,4,opt,name=source,proto3" json:"source,omitempty"`
	Hints         []string               `protobuf:"bytes,5,rep,name=hints,proto3" json:"hints,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClassifyInput) Reset() {
	*x = ClassifyInput{}
	mi := &file_internal_engine_grpc_proto_classifier_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClassifyInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClassifyInput) ProtoMessage() {}

func (x *ClassifyInput) ProtoReflect() protoreflect.Message {
	mi := &file_internal_engine_grpc_proto_classifier_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClassifyInput.ProtoReflect.Descriptor instead.
func (*ClassifyInput) Descriptor() ([]byte, []int) {
	return file_internal_engine_grpc_proto_classifier_proto_rawDescGZIP(), []int{1}
}

func (x *ClassifyInput) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ClassifyInput) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ClassifyInput) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *ClassifyInput) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *ClassifyInput) GetHints() []string {
	if x != nil {
		return x.Hints
	}
	return nil
}

// ClassifyResponse contains classification results.
type ClassifyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Output        *ClassifyOutput        `protobuf:"bytes,1,opt,name=output,proto3" json:"output,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClassifyResponse) Reset() {
	*x = ClassifyResponse{}
	mi := &file_internal_engine_grpc_proto_classifier_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClassifyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClassifyResponse) ProtoMessage() {}

func (x *ClassifyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_engine_grpc_proto_classifier_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClassifyResponse.ProtoReflect.Descriptor instead.
func (*ClassifyResponse) Descriptor() ([]byte, []int) {
	return file_internal_engine_grpc_proto_classifier_proto_rawDescGZIP(), []int{2}
}

func (x *ClassifyResponse) GetOutput() *ClassifyOutput {
	if x != nil {
		return x.Output
	}
	return nil
}

// ClassifyOutput contains the classification result.
type ClassifyOutput struct {
	state             protoimpl.MessageState       `protogen:"open.v1"`
	Id                string                       `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Category          string                       `protobuf:"bytes,2,opt,name=category,proto3" json:"category,omitempty"`
	Confidence        float64                      `protobuf:"fixed64,3,opt,name=confidence,proto3" json:"confidence,omitempty"`
	Alternatives      []*ClassificationAlternative `protobuf:"bytes,4,rep,name=alternatives,proto3" json:"alternatives,omitempty"`
	ExtractedEntities *ExtractedEntities           `protobuf:"bytes,5,opt,name=extracted_entities,json=extractedEntities,proto3" json:"extracted_entities,omitempty"`
	Explanation       string                       `protobuf:"bytes,6,opt,name=explanation,proto3" json:"explanation,omitempty"`
	RequiresReview    bool                         `protobuf:"varint,7,opt,name=requires_review,json=requiresReview,proto3" json:"requires_review,omitempty"`
	ReviewReason      string                       `protobuf:"bytes,8,opt,name=review_reason,json=reviewReason,proto3" json:"review_reason,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ClassifyOutput) Reset() {
	*x = ClassifyOutput{}
	mi := &file_internal_engine_grpc_proto_classifier_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClassifyOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClassifyOutput) ProtoMessage() {}

func (x *ClassifyOutput) ProtoReflect() protoreflect.Message {
	mi := &file_internal_engine_grpc_proto_classifier_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClassifyOutput.ProtoReflect.Descriptor instead.
func (*ClassifyOutput) Descriptor() ([]byte, []int) {
	return file_internal_engine_grpc_proto_classifier_proto_rawDescGZIP(), []int{3}
}

func (x *ClassifyOutput) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ClassifyOutput) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *ClassifyOutput) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *ClassifyOutput) GetAlternatives() []*ClassificationAlternative {
	if x != nil {
		return x.Alternatives
	}
	return nil
}

func (x *ClassifyOutput) GetExtractedEntities() *ExtractedEntities {
	if x != nil {
		return x.ExtractedEntities
	}
	return nil
}

func (x *ClassifyOutput) GetExplanation() string {
	if x != nil {
		return x.Explanation
	}
	return ""
}

func (x *ClassifyOutput) GetRequiresReview() bool {
	if x != nil {
		return x.RequiresReview
	}
	return false
}

func (x *ClassifyOutput) GetReviewReason() string {
	if x != nil {
		return x.ReviewReason
	}
	return ""
}

// ClassificationAlternative represents an alternative classification.
type ClassificationAlternative struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Category      string                 `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"`
	Confidence    float64                `protobuf:"fixed64,2,opt,name=confidence,proto3" json:"confidence,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClassificationAlternative) Reset() {
	*x = ClassificationAlternative{}
	mi := &file_internal_engine_grpc_proto_classifier_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClassificationAlternative) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClassificationAlternative) ProtoMessage() {}

func (x *ClassificationAlternative) ProtoReflect() protoreflect.Message {
	mi := &file_internal_engine_grpc_proto_classifier_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClassificationAlternative.ProtoReflect.Descriptor instead.
func (*ClassificationAlternative) Descriptor() ([]byte, []int) {
	return file_internal_engine_grpc_proto_classifier_proto_rawDescGZIP(), []int{4}
}

func (x *ClassificationAlternative) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *ClassificationAlternative) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *ClassificationAlternative) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// ExtractedEntities contains structured data extracted from content.
type ExtractedEntities struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	DueDate       string                 `protobuf:"bytes,3,opt,name=due_date,json=dueDate,proto3" json:"due_date,omitempty"`
	Duration      string                 `protobuf:"bytes,4,opt,name=duration,proto3" json:"duration,omitempty"`
	Priority      string                 `protobuf:"bytes,5,opt,name=priority,proto3" json:"priority,omitempty"`
	People        []string               `protobuf:"bytes,6,rep,name=people,proto3" json:"people,omitempty"`
	Tags          []string               `protobuf:"bytes,7,rep,name=tags,proto3" json:"tags,omitempty"`
	Urls          []string               `protobuf:"bytes,8,rep,name=urls,proto3" json:"urls,omitempty"`
	Custom        *structpb.Struct       `protobuf:"bytes,9,opt,name=custom,proto3" json:"custom,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExtractedEntities) Reset() {
	*x = ExtractedEntities{}
	mi := &file_internal_engine_grpc_proto_classifier_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtractedEntities) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtractedEntities) ProtoMessage() {}

func (x *ExtractedEntities) ProtoReflect() protoreflect.Message {
	mi := &file_internal_engine_grpc_proto_classifier_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtractedEntities.ProtoReflect.Descriptor instead.
func (*ExtractedEntities) Descriptor() ([]byte, []int) {
	return file_internal_engine_grpc_proto_classifier_proto_rawDescGZIP(), []int{5}
}

func (x *ExtractedEntities) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ExtractedEntities) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ExtractedEntities) GetDueDate() string {
	if x != nil {
		return x.DueDate
	}
	return ""
}

func (x *ExtractedEntities) GetDuration() string {
	if x != nil {
		return x.Duration
	}
	return ""
}

func (x *ExtractedEntities) GetPriority() string {
	if x != nil {
		return x.Priority
	}
	return ""
}

func (x *ExtractedEntities) GetPeople() []string {
	if x != nil {
		return x.People
	}
	return nil
}

func (x *ExtractedEntities) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *ExtractedEntities) GetUrls() []string {
	if x != nil {
		return x.Urls
	}
	return nil
}

func (x *ExtractedEntities) GetCustom() *structpb.Struct {
	if x != nil {
		return x.Custom
	}
	return nil
}

// BatchClassifyRequest contains multiple items to classify.
type BatchClassifyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Context       *ExecutionContext      `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	Inputs        []*ClassifyInput       `protobuf:"bytes,2,rep,name=inputs,proto3" json:"inputs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchClassifyRequest) Reset() {
	*x = BatchClassifyRequest{}
	mi := &file_internal_engine_grpc_proto_classifier_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchClassifyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchClassifyRequest) ProtoMessage() {}

func (x *BatchClassifyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_engine_grpc_proto_classifier_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchClassifyRequest.ProtoReflect.Descriptor instead.
func (*BatchClassifyRequest) Descriptor() ([]byte, []int) {
	return file_internal_engine_grpc_proto_classifier_proto_rawDescGZIP(), []int{6}
}

func (x *BatchClassifyRequest) GetContext() *ExecutionContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *BatchClassifyRequest) GetInputs() []*ClassifyInput {
	if x != nil {
		return x.Inputs
	}
	return nil
}

// BatchClassifyResponse contains results for all items.
type BatchClassifyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Outputs       []*ClassifyOutput      `protobuf:"bytes,1,rep,name=outputs,proto3" json:"outputs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchClassifyResponse) Reset() {
	*x = BatchClassifyResponse{}
	mi := &file_internal_engine_grpc_proto_classifier_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchClassifyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchClassifyResponse) ProtoMessage() {}

func (x *BatchClassifyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_engine_grpc_proto_classifier_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchClassifyResponse.ProtoReflect.Descriptor instead.
func (*BatchClassifyResponse) Descriptor() ([]byte, []int) {
	return file_internal_engine_grpc_proto_classifier_proto_rawDescGZIP(), []int{7}
}

func (x *BatchClassifyResponse) GetOutputs() []*ClassifyOutput {
	if x != nil {
		return x.Outputs
	}
	return nil
}

// GetCategoriesRequest requests supported categories.
type GetCategoriesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Context       *ExecutionContext      `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCategoriesRequest) Reset() {
	*x = GetCategoriesRequest{}
	mi := &file_internal_engine_grpc_proto_classifier_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCategoriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCategoriesRequest) ProtoMessage() {}

func (x *GetCategoriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_engine_grpc_proto_classifier_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCategoriesRequest.ProtoReflect.Descriptor instead.
func (*GetCategoriesRequest) Descriptor() ([]byte, []int) {
	return file_internal_engine_grpc_proto_classifier_proto_rawDescGZIP(), []int{8}
}

func (x *GetCategoriesRequest) GetContext() *ExecutionContext {
	if x != nil {
		return x.Context
	}
	return nil
}

// GetCategoriesResponse contains supported categories.
type GetCategoriesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Categories    []*Category            `protobuf:"bytes,1,rep,name=categories,proto3" json:"categories,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCategoriesResponse) Reset() {
	*x = GetCategoriesResponse{}
	mi := &file_internal_engine_grpc_proto_classifier_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCategoriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCategoriesResponse) ProtoMessage() {}

func (x *GetCategoriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_engine_grpc_proto_classifier_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCategoriesResponse.ProtoReflect.Descriptor instead.
func (*GetCategoriesResponse) Descriptor() ([]byte, []int) {
	return file_internal_engine_grpc_proto_classifier_proto_rawDescGZIP(), []int{9}
}

func (x *GetCategoriesResponse) GetCategories() []*Category {
	if x != nil {
		return x.Categories
	}
	return nil
}

// Category represents a classification category.
type Category struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Examples      []string               `protobuf:"bytes,4,rep,name=examples,proto3" json:"examples,omitempty"`
	Keywords      []string               `protobuf:"bytes,5,rep,name=keywords,proto3" json:"keywords,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Category) Reset() {
	*x = Category{}
	mi := &file_internal_engine_grpc_proto_classifier_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Category) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Category) ProtoMessage() {}

func (x *Category) ProtoReflect() protoreflect.Message {
	mi := &file_internal_engine_grpc_proto_classifier_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Category.ProtoReflect.Descriptor instead.
func (*Category) Descriptor() ([]byte, []int) {
	return file_internal_engine_grpc_proto_classifier_proto_rawDescGZIP(), []int{10}
}

func (x *Category) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Category) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Category) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Category) GetExamples() []string {
	if x != nil {
		return x.Examples
	}
	return nil
}

func (x *Category) GetKeywords() []string {
	if x != nil {
		return x.Keywords
	}
	return nil
}

var File_internal_engine_grpc_proto_classifier_proto protoreflect.FileDescriptor

const file_internal_engine_grpc_proto_classifier_proto_rawDesc = "" +
	"\n" +
	"+internal/engine/grpc/proto/classifier.proto\x12\x10orbita.engine.v1\x1a\x1cgoogle/protobuf/struct.proto\x1a'internal/engine/grpc/proto/engine.proto\"\x86\x01\n" +
	"\x0fClassifyRequest\x12<\n" +
	"\acontext\x18\x01 \x01(\v2\".orbita.engine.v1.ExecutionContextR\acontext\x125\n" +
	"\x05input\x18\x02 \x01(\v2\x1f.orbita.engine.v1.ClassifyInputR\x05input\"\xef\x01\n" +
	"\rClassifyInput\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12I\n" +
	"\bmetadata\x18\x03 \x03(\v2-.orbita.engine.v1.ClassifyInput.MetadataEntryR\bmetadata\x12\x16\n" +
	"\x06source\x18\x04 \x01(\tR\x06source\x12\x14\n" +
	"\x05hints\x18\x05 \x03(\tR\x05hints\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"L\n" +
	"\x10ClassifyResponse\x128\n" +
	"\x06output\x18\x01 \x01(\v2 .orbita.engine.v1.ClassifyOutputR\x06output\"\xf1\x02\n" +
	"\x0eClassifyOutput\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\bcategory\x18\x02 \x01(\tR\bcategory\x12\x1e\n" +
	"\n" +
	"confidence\x18\x03 \x01(\x01R\n" +
	"confidence\x12O\n" +
	"\falternatives\x18\x04 \x03(\v2+.orbita.engine.v1.ClassificationAlternativeR\falternatives\x12R\n" +
	"\x12extracted_entities\x18\x05 \x01(\v2#.orbita.engine.v1.ExtractedEntitiesR\x11extractedEntities\x12 \n" +
	"\vexplanation\x18\x06 \x01(\tR\vexplanation\x12'\n" +
	"\x0frequires_review\x18\a \x01(\bR\x0erequiresReview\x12#\n" +
	"\rreview_reason\x18\b \x01(\tR\freviewReason\"o\n" +
	"\x19ClassificationAlternative\x12\x1a\n" +
	"\bcategory\x18\x01 \x01(\tR\bcategory\x12\x1e\n" +
	"\n" +
	"confidence\x18\x02 \x01(\x01R\n" +
	"confidence\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"\x8f\x02\n" +
	"\x11ExtractedEntities\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x19\n" +
	"\bdue_date\x18\x03 \x01(\tR\adueDate\x12\x1a\n" +
	"\bduration\x18\x04 \x01(\tR\bduration\x12\x1a\n" +
	"\bpriority\x18\x05 \x01(\tR\bpriority\x12\x16\n" +
	"\x06people\x18\x06 \x03(\tR\x06people\x12\x12\n" +
	"\x04tags\x18\a \x03(\tR\x04tags\x12\x12\n" +
	"\x04urls\x18\b \x03(\tR\x04urls\x12/\n" +
	"\x06custom\x18\t \x01(\v2\x17.google.protobuf.StructR\x06custom\"\x8d\x01\n" +
	"\x14BatchClassifyRequest\x12<\n" +
	"\acontext\x18\x01 \x01(\v2\".orbita.engine.v1.ExecutionContextR\acontext\x127\n" +
	"\x06inputs\x18\x02 \x03(\v2\x1f.orbita.engine.v1.ClassifyInputR\x06inputs\"S\n" +
	"\x15BatchClassifyResponse\x12:\n" +
	"\aoutputs\x18\x01 \x03(\v2 .orbita.engine.v1.ClassifyOutputR\aoutputs\"T\n" +
	"\x14GetCategoriesRequest\x12<\n" +
	"\acontext\x18\x01 \x01(\v2\".orbita.engine.v1.ExecutionContextR\acontext\"S\n" +
	"\x15GetCategoriesResponse\x12:\n" +
	"\n" +
	"categories\x18\x01 \x03(\v2\x1a.orbita.engine.v1.CategoryR\n" +
	"categories\"\x88\x01\n" +
	"\bCategory\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1a\n" +
	"\bexamples\x18\x04 \x03(\tR\bexamples\x12\x1a\n" +
	"\bkeywords\x18\x05 \x03(\tR\bkeywords2\xa9\x02\n" +
	"\x10ClassifierEngine\x12Q\n" +
	"\bClassify\x12!.orbita.engine.v1.ClassifyRequest\x1a\".orbita.engine.v1.ClassifyResponse\x12`\n" +
	"\rBatchClassify\x12&.orbita.engine.v1.BatchClassifyRequest\x1a'.orbita.engine.v1.BatchClassifyResponse\x12`\n" +
	"\rGetCategories\x12&.orbita.engine.v1.GetCategoriesRequest\x1a'.orbita.engine.v1.GetCategoriesResponseBEZCgithub.com/felixgeelhaar/orbita/internal/engine/grpc/proto;enginepbb\x06proto3"

var (
	file_internal_engine_grpc_proto_classifier_proto_rawDescOnce sync.Once
	file_internal_engine_grpc_proto_classifier_proto_rawDescData []byte
)

func file_internal_engine_grpc_proto_classifier_proto_rawDescGZIP() []byte {
	file_internal_engine_grpc_proto_classifier_proto_rawDescOnce.Do(func() {
		file_internal_engine_grpc_proto_classifier_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_engine_grpc_proto_classifier_proto_rawDesc), len(file_internal_engine_grpc_proto_classifier_proto_rawDesc)))
	})
	return file_internal_engine_grpc_proto_classifier_proto_rawDescData
}

var file_internal_engine_grpc_proto_classifier_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_internal_engine_grpc_proto_classifier_proto_goTypes = []any{
	(*ClassifyRequest)(nil),           // 0: orbita.engine.v1.ClassifyRequest
	(*ClassifyInput)(nil),             // 1: orbita.engine.v1.ClassifyInput
	(*ClassifyResponse)(nil),          // 2: orbita.engine.v1.ClassifyResponse
	(*ClassifyOutput)(nil),            // 3: orbita.engine.v1.ClassifyOutput
	(*ClassificationAlternative)(nil), // 4: orbita.engine.v1.ClassificationAlternative
	(*ExtractedEntities)(nil),         // 5: orbita.engine.v1.ExtractedEntities
	(*BatchClassifyRequest)(nil),      // 6: orbita.engine.v1.BatchClassifyRequest
	(*BatchClassifyResponse)(nil),     // 7: orbita.engine.v1.BatchClassifyResponse
	(*GetCategoriesRequest)(nil),      // 8: orbita.engine.v1.GetCategoriesRequest
	(*GetCategoriesResponse)(nil),     // 9: orbita.engine.v1.GetCategoriesResponse
	(*Category)(nil),                  // 10: orbita.engine.v1.Category
	nil,                               // 11: orbita.engine.v1.ClassifyInput.MetadataEntry
	(*ExecutionContext)(nil),          // 12: orbita.engine.v1.ExecutionContext
	(*structpb.Struct)(nil),           // 13: google.protobuf.Struct
}
var file_internal_engine_grpc_proto_classifier_proto_depIdxs = []int32{
	12, // 0: orbita.engine.v1.ClassifyRequest.context:type_name -> orbita.engine.v1.ExecutionContext
	1,  // 1: orbita.engine.v1.ClassifyRequest.input:type_name -> orbita.engine.v1.ClassifyInput
	11, // 2: orbita.engine.v1.ClassifyInput.metadata:type_name -> orbita.engine.v1.ClassifyInput.MetadataEntry
	3,  // 3: orbita.engine.v1.ClassifyResponse.output:type_name -> orbita.engine.v1.ClassifyOutput
	4,  // 4: orbita.engine.v1.ClassifyOutput.alternatives:type_name -> orbita.engine.v1.ClassificationAlternative
	5,  // 5: orbita.engine.v1.ClassifyOutput.extracted_entities:type_name -> orbita.engine.v1.ExtractedEntities
	13, // 6: orbita.engine.v1.ExtractedEntities.custom:type_name -> google.protobuf.Struct
	12, // 7: orbita.engine.v1.BatchClassifyRequest.context:type_name -> orbita.engine.v1.ExecutionContext
	1,  // 8: orbita.engine.v1.BatchClassifyRequest.inputs:type_name -> orbita.engine.v1.ClassifyInput
	3,  // 9: orbita.engine.v1.BatchClassifyResponse.outputs:type_name -> orbita.engine.v1.ClassifyOutput
	12, // 10: orbita.engine.v1.GetCategoriesRequest.context:type_name -> orbita.engine.v1.ExecutionContext
	10, // 11: orbita.engine.v1.GetCategoriesResponse.categories:type_name -> orbita.engine.v1.Category
	0,  // 12: orbita.engine.v1.ClassifierEngine.Classify:input_type -> orbita.engine.v1.ClassifyRequest
	6,  // 13: orbita.engine.v1.ClassifierEngine.BatchClassify:input_type -> orbita.engine.v1.BatchClassifyRequest
	8,  // 14: orbita.engine.v1.ClassifierEngine.GetCategories:input_type -> orbita.engine.v1.GetCategoriesRequest
	2,  // 15: orbita.engine.v1.ClassifierEngine.Classify:output_type -> orbita.engine.v1.ClassifyResponse
	7,  // 16: orbita.engine.v1.ClassifierEngine.BatchClassify:output_type -> orbita.engine.v1.BatchClassifyResponse
	9,  // 17: orbita.engine.v1.ClassifierEngine.GetCategories:output_type -> orbita.engine.v1.GetCategoriesResponse
	15, // [15:18] is the sub-list for method output_type
	12, // [12:15] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_internal_engine_grpc_proto_classifier_proto_init() }
func file_internal_engine_grpc_proto_classifier_proto_init() {
	if File_internal_engine_grpc_proto_classifier_proto != nil {
		return
	}
	file_internal_engine_grpc_proto_engine_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_engine_grpc_proto_classifier_proto_rawDesc), len(file_internal_engine_grpc_proto_classifier_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_engine_grpc_proto_classifier_proto_goTypes,
		DependencyIndexes: file_internal_engine_grpc_proto_classifier_proto_depIdxs,
		MessageInfos:      file_internal_engine_grpc_proto_classifier_proto_msgTypes,
	}.Build()
	File_internal_engine_grpc_proto_classifier_proto = out.File
	file_internal_engine_grpc_proto_classifier_proto_goTypes = nil
	file_internal_engine_grpc_proto_classifier_proto_depIdxs = nil
}
