// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: internal/engine/grpc/proto/classifier.proto

package enginepb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ClassifierEngine_Classify_FullMethodName      = "/orbita.engine.v1.ClassifierEngine/Classify"
	ClassifierEngine_BatchClassify_FullMethodName = "/orbita.engine.v1.ClassifierEngine/BatchClassify"
	ClassifierEngine_GetCategories_FullMethodName = "/orbita.engine.v1.ClassifierEngine/GetCategories"
)

// ClassifierEngineClient is the client API for ClassifierEngine service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ClassifierEngine provides classification capabilities.
type ClassifierEngineClient interface {
	// Classify analyzes content and returns classification results.
	Classify(ctx context.Context, in *ClassifyRequest, opts ...grpc.CallOption) (*ClassifyResponse, error)
	// BatchClassify classifies multiple items.
	BatchClassify(ctx context.Context, in *BatchClassifyRequest, opts ...grpc.CallOption) (*BatchClassifyResponse, error)
	// GetCategories returns supported categories.
	GetCategories(ctx context.Context, in *GetCategoriesRequest, opts ...grpc.CallOption) (*GetCategoriesResponse, error)
}

type classifierEngineClient struct {
	cc grpc.ClientConnInterface
}

func NewClassifierEngineClient(cc grpc.ClientConnInterface) ClassifierEngineClient {
	return &classifierEngineClient{cc}
}

func (c *classifierEngineClient) Classify(ctx context.Context, in *ClassifyRequest, opts ...grpc.CallOption) (*ClassifyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClassifyResponse)
	err := c.cc.Invoke(ctx, ClassifierEngine_Classify_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *classifierEngineClient) BatchClassify(ctx context.Context, in *BatchClassifyRequest, opts ...grpc.CallOption) (*BatchClassifyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchClassifyResponse)
	err := c.cc.Invoke(ctx, ClassifierEngine_BatchClassify_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *classifierEngineClient) GetCategories(ctx context.Context, in *GetCategoriesRequest, opts ...grpc.CallOption) (*GetCategoriesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCategoriesResponse)
	err := c.cc.Invoke(ctx, ClassifierEngine_GetCategories_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ClassifierEngineServer is the server API for ClassifierEngine service.
// All implementations must embed UnimplementedClassifierEngineServer
// for forward compatibility.
//
// ClassifierEngine provides classification capabilities.
type ClassifierEngineServer interface {
	// Classify analyzes content and returns classification results.
	Classify(context.Context, *ClassifyRequest) (*ClassifyResponse, error)
	// BatchClassify classifies multiple items.
	BatchClassify(context.Context, *BatchClassifyRequest) (*BatchClassifyResponse, error)
	// GetCategories returns supported categories.
	GetCategories(context.Context, *GetCategoriesRequest) (*GetCategoriesResponse, error)
	mustEmbedUnimplementedClassifierEngineServer()
}

// UnimplementedClassifierEngineServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedClassifierEngineServer struct{}

func (UnimplementedClassifierEngineServer) Classify(context.Context, *ClassifyRequest) (*ClassifyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Classify not implemented")
}
func (UnimplementedClassifierEngineServer) BatchClassify(context.Context, *BatchClassifyRequest) (*BatchClassifyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BatchClassify not implemented")
}
func (UnimplementedClassifierEngineServer) GetCategories(context.Context, *GetCategoriesRequest) (*GetCategoriesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCategories not implemented")
}
func (UnimplementedClassifierEngineServer) mustEmbedUnimplementedClassifierEngineServer() {}
func (UnimplementedClassifierEngineServer) testEmbeddedByValue()                          {}

// UnsafeClassifierEngineServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ClassifierEngineServer will
// result in compilation errors.
type UnsafeClassifierEngineServer interface {
	mustEmbedUnimplementedClassifierEngineServer()
}

func RegisterClassifierEngineServer(s grpc.ServiceRegistrar, srv ClassifierEngineServer) {
	// If the following call panics, it indicates UnimplementedClassifierEngineServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ClassifierEngine_ServiceDesc, srv)
}

func _ClassifierEngine_Classify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClassifyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClassifierEngineServer).Classify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClassifierEngine_Classify_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClassifierEngineServer).Classify(ctx, req.(*ClassifyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClassifierEngine_BatchClassify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchClassifyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClassifierEngineServer).BatchClassify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClassifierEngine_BatchClassify_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClassifierEngineServer).BatchClassify(ctx, req.(*BatchClassifyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClassifierEngine_GetCategories_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCategoriesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClassifierEngineServer).GetCategories(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClassifierEngine_GetCategories_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClassifierEngineServer).GetCategories(ctx, req.(*GetCategoriesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ClassifierEngine_ServiceDesc is the grpc.ServiceDesc for ClassifierEngine service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ClassifierEngine_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "orbita.engine.v1.ClassifierEngine",
	HandlerType: (*ClassifierEngineServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Classify",
			Handler:    _ClassifierEngine_Classify_Handler,
		},
		{
			MethodName: "BatchClassify",
			Handler:    _ClassifierEngine_BatchClassify_Handler,
		},
		{
			MethodName: "GetCategories",
			Handler:    _ClassifierEngine_GetCategories_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/engine/grpc/proto/classifier.proto",
}
