// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: internal/engine/grpc/proto/engine.proto

package enginepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// EngineType identifies the type of engine.
type EngineType int32

const (
	EngineType_ENGINE_TYPE_UNSPECIFIED EngineType = 0
	EngineType_ENGINE_TYPE_SCHEDULER   EngineType = 1
	EngineType_ENGINE_TYPE_PRIORITY    EngineType = 2
	EngineType_ENGINE_TYPE_CLASSIFIER  EngineType = 3
	EngineType_ENGINE_TYPE_AUTOMATION  EngineType = 4
)

// Enum value maps for EngineType.
var (
	EngineType_name = map[int32]string{
		0: "ENGINE_TYPE_UNSPECIFIED",
		1: "ENGINE_TYPE_SCHEDULER",
		2: "ENGINE_TYPE_PRIORITY",
		3: "ENGINE_TYPE_CLASSIFIER",
		4: "ENGINE_TYPE_AUTOMATION",
	}
	EngineType_value = map[string]int32{
		"ENGINE_TYPE_UNSPECIFIED": 0,
		"ENGINE_TYPE_SCHEDULER":   1,
		"ENGINE_TYPE_PRIORITY":    2,
		"ENGINE_TYPE_CLASSIFIER":  3,
		"ENGINE_TYPE_AUTOMATION":  4,
	}
)

func (x EngineType) Enum() *EngineType {
	p := new(EngineType)
	*p = x
	return p
}

func (x EngineType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EngineType) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_engine_grpc_proto_engine_proto_enumTypes[0].Descriptor()
}

func (EngineType) Type() protoreflect.EnumType {
	return &file_internal_engine_grpc_proto_engine_proto_enumTypes[0]
}

func (x EngineType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EngineType.Descriptor instead.
func (EngineType) EnumDescriptor() ([]byte, []int) {
	return file_internal_engine_grpc_proto_engine_proto_rawDescGZIP(), []int{0}
}

// MetadataRequest is the request for Metadata RPC.
type MetadataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetadataRequest) Reset() {
	*x = MetadataRequest{}
	mi := &file_internal_engine_grpc_proto_engine_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetadataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetadataRequest) ProtoMessage() {}

func (x *MetadataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_engine_grpc_proto_engine_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetadataRequest.ProtoReflect.Descriptor instead.
func (*MetadataRequest) Descriptor() ([]byte, []int) {
	return file_internal_engine_grpc_proto_engine_proto_rawDescGZIP(), []int{0}
}

// MetadataResponse contains engine metadata.
type MetadataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	Author        string                 `protobuf:"bytes,4,opt,name=author,proto3" json:"author,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	License       string                 `protobuf:"bytes,6,opt,name=license,proto3" json:"license,omitempty"`
	Homepage      string                 `protobuf:"bytes,7,opt,name=homepage,proto3" json:"homepage,omitempty"`
	Tags          []string               `protobuf:"bytes,8,rep,name=tags,proto3" json:"tags,omitempty"`
	MinApiVersion string                 `protobuf:"bytes,9,opt,name=min_api_version,json=minApiVersion,proto3" json:"min_api_version,omitempty"`
	Capabilities  []string               `protobuf:"bytes,10,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	Type          EngineType             `protobuf:"varint,11,opt,name=type,proto3,enum=orbita.engine.v1.EngineType" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetadataResponse) Reset() {
	*x = MetadataResponse{}
	mi := &file_internal_engine_grpc_proto_engine_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetadataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetadataResponse) ProtoMessage() {}

func (x *MetadataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_engine_grpc_proto_engine_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetadataResponse.ProtoReflect.Descriptor instead.
func (*MetadataResponse) Descriptor() ([]byte, []int) {
	return file_internal_engine_grpc_proto_engine_proto_rawDescGZIP(), []int{1}
}

func (x *MetadataResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MetadataResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MetadataResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *MetadataResponse) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *MetadataResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *MetadataResponse) GetLicense() string {
	if x != nil {
		return x.License
	}
	return ""
}

func (x *MetadataResponse) GetHomepage() string {
	if x != nil {
		return x.Homepage
	}
	return ""
}

func (x *MetadataResponse) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *MetadataResponse) GetMinApiVersion() string {
	if x != nil {
		return x.MinApiVersion
	}
	return ""
}

func (x *MetadataResponse) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *MetadataResponse) GetType() EngineType {
	if x != nil {
		return x.Type
	}
	return EngineType_ENGINE_TYPE_UNSPECIFIED
}

// ConfigSchemaRequest is the request for ConfigSchema RPC.
type ConfigSchemaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigSchemaRequest) Reset() {
	*x = ConfigSchemaRequest{}
	mi := &file_internal_engine_grpc_proto_engine_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigSchemaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigSchemaRequest) ProtoMessage() {}

func (x *ConfigSchemaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_engine_grpc_proto_engine_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigSchemaRequest.ProtoReflect.Descriptor instead.
func (*ConfigSchemaRequest) Descriptor() ([]byte, []int) {
	return file_internal_engine_grpc_proto_engine_proto_rawDescGZIP(), []int{2}
}

// ConfigSchemaResponse contains the configuration schema.
type ConfigSchemaResponse struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Schema        string                     `protobuf:"bytes,1,opt,name=schema,proto3" json:"schema,omitempty"` // JSON Schema version
	Type          string                     `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`     // Always "object"
	Title         string                     `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                     `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Properties    map[string]*PropertySchema `protobuf:"bytes,5,rep,name=properties,proto3" json:"properties,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Required      []string                   `protobuf:"bytes,6,rep,name=required,proto3" json:"required,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigSchemaResponse) Reset() {
	*x = ConfigSchemaResponse{}
	mi := &file_internal_engine_grpc_proto_engine_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigSchemaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigSchemaResponse) ProtoMessage() {}

func (x *ConfigSchemaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_engine_grpc_proto_engine_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigSchemaResponse.ProtoReflect.Descriptor instead.
func (*ConfigSchemaResponse) Descriptor() ([]byte, []int) {
	return file_internal_engine_grpc_proto_engine_proto_rawDescGZIP(), []int{3}
}

func (x *ConfigSchemaResponse) GetSchema() string {
	if x != nil {
		return x.Schema
	}
	return ""
}

func (x *ConfigSchemaResponse) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ConfigSchemaResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ConfigSchemaResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ConfigSchemaResponse) GetProperties() map[string]*PropertySchema {
	if x != nil {
		return x.Properties
	}
	return nil
}

func (x *ConfigSchemaResponse) GetRequired() []string {
	if x != nil {
		return x.Required
	}
	return nil
}

// PropertySchema defines a configuration property.
type PropertySchema struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Default       *structpb.Value        `protobuf:"bytes,4,opt,name=default,proto3" json:"default,omitempty"`
	Enum          []*structpb.Value      `protobuf:"bytes,5,rep,name=enum,proto3" json:"enum,omitempty"`
	Minimum       *float64               `protobuf:"fixed64,6,opt,name=minimum,proto3,oneof" json:"minimum,omitempty"`
	Maximum       *float64               `protobuf:"fixed64,7,opt,name=maximum,proto3,oneof" json:"maximum,omitempty"`
	MinLength     *int32                 `protobuf:"varint,8,opt,name=min_length,json=minLength,proto3,oneof" json:"min_length,omitempty"`
	MaxLength     *int32                 `protobuf:"varint,9,opt,name=max_length,json=maxLength,proto3,oneof" json:"max_length,omitempty"`
	Pattern       string                 `protobuf:"bytes,10,opt,name=pattern,proto3" json:"pattern,omitempty"`
	Format        string                 `protobuf:"bytes,11,opt,name=format,proto3" json:"format,omitempty"`
	Items         *PropertySchema        `protobuf:"bytes,12,opt,name=items,proto3" json:"items,omitempty"`
	UiHints       *UIHints               `protobuf:"bytes,13,opt,name=ui_hints,json=uiHints,proto3" json:"ui_hints,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PropertySchema) Reset() {
	*x = PropertySchema{}
	mi := &file_internal_engine_grpc_proto_engine_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PropertySchema) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PropertySchema) ProtoMessage() {}

func (x *PropertySchema) ProtoReflect() protoreflect.Message {
	mi := &file_internal_engine_grpc_proto_engine_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PropertySchema.ProtoReflect.Descriptor instead.
func (*PropertySchema) Descriptor() ([]byte, []int) {
	return file_internal_engine_grpc_proto_engine_proto_rawDescGZIP(), []int{4}
}

func (x *PropertySchema) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *PropertySchema) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *PropertySchema) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *PropertySchema) GetDefault() *structpb.Value {
	if x != nil {
		return x.Default
	}
	return nil
}

func (x *PropertySchema) GetEnum() []*structpb.Value {
	if x != nil {
		return x.Enum
	}
	return nil
}

func (x *PropertySchema) GetMinimum() float64 {
	if x != nil && x.Minimum != nil {
		return *x.Minimum
	}
	return 0
}

func (x *PropertySchema) GetMaximum() float64 {
	if x != nil && x.Maximum != nil {
		return *x.Maximum
	}
	return 0
}

func (x *PropertySchema) GetMinLength() int32 {
	if x != nil && x.MinLength != nil {
		return *x.MinLength
	}
	return 0
}

func (x *PropertySchema) GetMaxLength() int32 {
	if x != nil && x.MaxLength != nil {
		return *x.MaxLength
	}
	return 0
}

func (x *PropertySchema) GetPattern() string {
	if x != nil {
		return x.Pattern
	}
	return ""
}

func (x *PropertySchema) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *PropertySchema) GetItems() *PropertySchema {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *PropertySchema) GetUiHints() *UIHints {
	if x != nil {
		return x.UiHints
	}
	return nil
}

// UIHints provides rendering hints for UI generation.
type UIHints struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Widget        string                 `protobuf:"bytes,1,opt,name=widget,proto3" json:"widget,omitempty"`
	Placeholder   string                 `protobuf:"bytes,2,opt,name=placeholder,proto3" json:"placeholder,omitempty"`
	HelpText      string                 `protobuf:"bytes,3,opt,name=help_text,json=helpText,proto3" json:"help_text,omitempty"`
	Group         string                 `protobuf:"bytes,4,opt,name=group,proto3" json:"group,omitempty"`
	Order         int32                  `protobuf:"varint,5,opt,name=order,proto3" json:"order,omitempty"`
	Advanced      bool                   `protobuf:"varint,6,opt,name=advanced,proto3" json:"advanced,omitempty"`
	Disabled      bool                   `protobuf:"varint,7,opt,name=disabled,proto3" json:"disabled,omitempty"`
	Visible       *VisibilityCondition   `protobuf:"bytes,8,opt,name=visible,proto3" json:"visible,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UIHints) Reset() {
	*x = UIHints{}
	mi := &file_internal_engine_grpc_proto_engine_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UIHints) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UIHints) ProtoMessage() {}

func (x *UIHints) ProtoReflect() protoreflect.Message {
	mi := &file_internal_engine_grpc_proto_engine_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UIHints.ProtoReflect.Descriptor instead.
func (*UIHints) Descriptor() ([]byte, []int) {
	return file_internal_engine_grpc_proto_engine_proto_rawDescGZIP(), []int{5}
}

func (x *UIHints) GetWidget() string {
	if x != nil {
		return x.Widget
	}
	return ""
}

func (x *UIHints) GetPlaceholder() string {
	if x != nil {
		return x.Placeholder
	}
	return ""
}

func (x *UIHints) GetHelpText() string {
	if x != nil {
		return x.HelpText
	}
	return ""
}

func (x *UIHints) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *UIHints) GetOrder() int32 {
	if x != nil {
		return x.Order
	}
	return 0
}

func (x *UIHints) GetAdvanced() bool {
	if x != nil {
		return x.Advanced
	}
	return false
}

func (x *UIHints) GetDisabled() bool {
	if x != nil {
		return x.Disabled
	}
	return false
}

func (x *UIHints) GetVisible() *VisibilityCondition {
	if x != nil {
		return x.Visible
	}
	return nil
}

// VisibilityCondition defines field visibility rules.
type VisibilityCondition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Field         string                 `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	Operator      string                 `protobuf:"bytes,2,opt,name=operator,proto3" json:"operator,omitempty"`
	Value         *structpb.Value        `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VisibilityCondition) Reset() {
	*x = VisibilityCondition{}
	mi := &file_internal_engine_grpc_proto_engine_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VisibilityCondition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VisibilityCondition) ProtoMessage() {}

func (x *VisibilityCondition) ProtoReflect() protoreflect.Message {
	mi := &file_internal_engine_grpc_proto_engine_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VisibilityCondition.ProtoReflect.Descriptor instead.
func (*VisibilityCondition) Descriptor() ([]byte, []int) {
	return file_internal_engine_grpc_proto_engine_proto_rawDescGZIP(), []int{6}
}

func (x *VisibilityCondition) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *VisibilityCondition) GetOperator() string {
	if x != nil {
		return x.Operator
	}
	return ""
}

func (x *VisibilityCondition) GetValue() *structpb.Value {
	if x != nil {
		return x.Value
	}
	return nil
}

// InitializeRequest contains engine initialization parameters.
type InitializeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EngineId      string                 `protobuf:"bytes,1,opt,name=engine_id,json=engineId,proto3" json:"engine_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Config        *structpb.Struct       `protobuf:"bytes,3,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitializeRequest) Reset() {
	*x = InitializeRequest{}
	mi := &file_internal_engine_grpc_proto_engine_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitializeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitializeRequest) ProtoMessage() {}

func (x *InitializeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_engine_grpc_proto_engine_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitializeRequest.ProtoReflect.Descriptor instead.
func (*InitializeRequest) Descriptor() ([]byte, []int) {
	return file_internal_engine_grpc_proto_engine_proto_rawDescGZIP(), []int{7}
}

func (x *InitializeRequest) GetEngineId() string {
	if x != nil {
		return x.EngineId
	}
	return ""
}

func (x *InitializeRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *InitializeRequest) GetConfig() *structpb.Struct {
	if x != nil {
		return x.Config
	}
	return nil
}

// InitializeResponse is the response from Initialize.
type InitializeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitializeResponse) Reset() {
	*x = InitializeResponse{}
	mi := &file_internal_engine_grpc_proto_engine_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitializeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitializeResponse) ProtoMessage() {}

func (x *InitializeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_engine_grpc_proto_engine_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitializeResponse.ProtoReflect.Descriptor instead.
func (*InitializeResponse) Descriptor() ([]byte, []int) {
	return file_internal_engine_grpc_proto_engine_proto_rawDescGZIP(), []int{8}
}

func (x *InitializeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *InitializeResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// HealthCheckRequest is the request for HealthCheck RPC.
type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_internal_engine_grpc_proto_engine_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_engine_grpc_proto_engine_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_internal_engine_grpc_proto_engine_proto_rawDescGZIP(), []int{9}
}

// HealthCheckResponse contains the health status.
type HealthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Healthy       bool                   `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Details       *structpb.Struct       `protobuf:"bytes,3,opt,name=details,proto3" json:"details,omitempty"`
	CheckedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=checked_at,json=checkedAt,proto3" json:"checked_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_internal_engine_grpc_proto_engine_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_engine_grpc_proto_engine_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_internal_engine_grpc_proto_engine_proto_rawDescGZIP(), []int{10}
}

func (x *HealthCheckResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *HealthCheckResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *HealthCheckResponse) GetDetails() *structpb.Struct {
	if x != nil {
		return x.Details
	}
	return nil
}

func (x *HealthCheckResponse) GetCheckedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CheckedAt
	}
	return nil
}

// ShutdownRequest is the request for Shutdown RPC.
type ShutdownRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShutdownRequest) Reset() {
	*x = ShutdownRequest{}
	mi := &file_internal_engine_grpc_proto_engine_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShutdownRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownRequest) ProtoMessage() {}

func (x *ShutdownRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_engine_grpc_proto_engine_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownRequest.ProtoReflect.Descriptor instead.
func (*ShutdownRequest) Descriptor() ([]byte, []int) {
	return file_internal_engine_grpc_proto_engine_proto_rawDescGZIP(), []int{11}
}

// ShutdownResponse is the response from Shutdown.
type ShutdownResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShutdownResponse) Reset() {
	*x = ShutdownResponse{}
	mi := &file_internal_engine_grpc_proto_engine_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShutdownResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownResponse) ProtoMessage() {}

func (x *ShutdownResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_engine_grpc_proto_engine_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownResponse.ProtoReflect.Descriptor instead.
func (*ShutdownResponse) Descriptor() ([]byte, []int) {
	return file_internal_engine_grpc_proto_engine_proto_rawDescGZIP(), []int{12}
}

func (x *ShutdownResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ShutdownResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// ExecutionContext provides context for engine operations.
type ExecutionContext struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	EngineId      string                 `protobuf:"bytes,2,opt,name=engine_id,json=engineId,proto3" json:"engine_id,omitempty"`
	RequestId     string                 `protobuf:"bytes,3,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	StartTime     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecutionContext) Reset() {
	*x = ExecutionContext{}
	mi := &file_internal_engine_grpc_proto_engine_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutionContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutionContext) ProtoMessage() {}

func (x *ExecutionContext) ProtoReflect() protoreflect.Message {
	mi := &file_internal_engine_grpc_proto_engine_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutionContext.ProtoReflect.Descriptor instead.
func (*ExecutionContext) Descriptor() ([]byte, []int) {
	return file_internal_engine_grpc_proto_engine_proto_rawDescGZIP(), []int{13}
}

func (x *ExecutionContext) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ExecutionContext) GetEngineId() string {
	if x != nil {
		return x.EngineId
	}
	return ""
}

func (x *ExecutionContext) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ExecutionContext) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

var File_internal_engine_grpc_proto_engine_proto protoreflect.FileDescriptor

const file_internal_engine_grpc_proto_engine_proto_rawDesc = "" +
	"\n" +
	"'internal/engine/grpc/proto/engine.proto\x12\x10orbita.engine.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/protobuf/struct.proto\"\x11\n" +
	"\x0fMetadataRequest\"\xd2\x02\n" +
	"\x10MetadataResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12\x16\n" +
	"\x06author\x18\x04 \x01(\tR\x06author\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x18\n" +
	"\alicense\x18\x06 \x01(\tR\alicense\x12\x1a\n" +
	"\bhomepage\x18\a \x01(\tR\bhomepage\x12\x12\n" +
	"\x04tags\x18\b \x03(\tR\x04tags\x12&\n" +
	"\x0fmin_api_version\x18\t \x01(\tR\rminApiVersion\x12\"\n" +
	"\fcapabilities\x18\n" +
	" \x03(\tR\fcapabilities\x120\n" +
	"\x04type\x18\v \x01(\x0e2\x1c.orbita.engine.v1.EngineTypeR\x04type\"\x15\n" +
	"\x13ConfigSchemaRequest\"\xcf\x02\n" +
	"\x14ConfigSchemaResponse\x12\x16\n" +
	"\x06schema\x18\x01 \x01(\tR\x06schema\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12V\n" +
	"\n" +
	"properties\x18\x05 \x03(\v26.orbita.engine.v1.ConfigSchemaResponse.PropertiesEntryR\n" +
	"properties\x12\x1a\n" +
	"\brequired\x18\x06 \x03(\tR\brequired\x1a_\n" +
	"\x0fPropertiesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x126\n" +
	"\x05value\x18\x02 \x01(\v2 .orbita.engine.v1.PropertySchemaR\x05value:\x028\x01\"\x96\x04\n" +
	"\x0ePropertySchema\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x120\n" +
	"\adefault\x18\x04 \x01(\v2\x16.google.protobuf.ValueR\adefault\x12*\n" +
	"\x04enum\x18\x05 \x03(\v2\x16.google.protobuf.ValueR\x04enum\x12\x1d\n" +
	"\aminimum\x18\x06 \x01(\x01H\x00R\aminimum\x88\x01\x01\x12\x1d\n" +
	"\amaximum\x18\a \x01(\x01H\x01R\amaximum\x88\x01\x01\x12\"\n" +
	"\n" +
	"min_length\x18\b \x01(\x05H\x02R\tminLength\x88\x01\x01\x12\"\n" +
	"\n" +
	"max_length\x18\t \x01(\x05H\x03R\tmaxLength\x88\x01\x01\x12\x18\n" +
	"\apattern\x18\n" +
	" \x01(\tR\apattern\x12\x16\n" +
	"\x06format\x18\v \x01(\tR\x06format\x126\n" +
	"\x05items\x18\f \x01(\v2 .orbita.engine.v1.PropertySchemaR\x05items\x124\n" +
	"\bui_hints\x18\r \x01(\v2\x19.orbita.engine.v1.UIHintsR\auiHintsB\n" +
	"\n" +
	"\b_minimumB\n" +
	"\n" +
	"\b_maximumB\r\n" +
	"\v_min_lengthB\r\n" +
	"\v_max_length\"\x85\x02\n" +
	"\aUIHints\x12\x16\n" +
	"\x06widget\x18\x01 \x01(\tR\x06widget\x12 \n" +
	"\vplaceholder\x18\x02 \x01(\tR\vplaceholder\x12\x1b\n" +
	"\thelp_text\x18\x03 \x01(\tR\bhelpText\x12\x14\n" +
	"\x05group\x18\x04 \x01(\tR\x05group\x12\x14\n" +
	"\x05order\x18\x05 \x01(\x05R\x05order\x12\x1a\n" +
	"\badvanced\x18\x06 \x01(\bR\badvanced\x12\x1a\n" +
	"\bdisabled\x18\a \x01(\bR\bdisabled\x12?\n" +
	"\avisible\x18\b \x01(\v2%.orbita.engine.v1.VisibilityConditionR\avisible\"u\n" +
	"\x13VisibilityCondition\x12\x14\n" +
	"\x05field\x18\x01 \x01(\tR\x05field\x12\x1a\n" +
	"\boperator\x18\x02 \x01(\tR\boperator\x12,\n" +
	"\x05value\x18\x03 \x01(\v2\x16.google.protobuf.ValueR\x05value\"z\n" +
	"\x11InitializeRequest\x12\x1b\n" +
	"\tengine_id\x18\x01 \x01(\tR\bengineId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12/\n" +
	"\x06config\x18\x03 \x01(\v2\x17.google.protobuf.StructR\x06config\"D\n" +
	"\x12InitializeResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\x14\n" +
	"\x12HealthCheckRequest\"\xb7\x01\n" +
	"\x13HealthCheckResponse\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x121\n" +
	"\adetails\x18\x03 \x01(\v2\x17.google.protobuf.StructR\adetails\x129\n" +
	"\n" +
	"checked_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcheckedAt\"\x11\n" +
	"\x0fShutdownRequest\"B\n" +
	"\x10ShutdownResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\xa2\x01\n" +
	"\x10ExecutionContext\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tengine_id\x18\x02 \x01(\tR\bengineId\x12\x1d\n" +
	"\n" +
	"request_id\x18\x03 \x01(\tR\trequestId\x129\n" +
	"\n" +
	"start_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime*\x96\x01\n" +
	"\n" +
	"EngineType\x12\x1b\n" +
	"\x17ENGINE_TYPE_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15ENGINE_TYPE_SCHEDULER\x10\x01\x12\x18\n" +
	"\x14ENGINE_TYPE_PRIORITY\x10\x02\x12\x1a\n" +
	"\x16ENGINE_TYPE_CLASSIFIER\x10\x03\x12\x1a\n" +
	"\x16ENGINE_TYPE_AUTOMATION\x10\x042\xc2\x03\n" +
	"\x06Engine\x12Q\n" +
	"\bMetadata\x12!.orbita.engine.v1.MetadataRequest\x1a\".orbita.engine.v1.MetadataResponse\x12]\n" +
	"\fConfigSchema\x12%.orbita.engine.v1.ConfigSchemaRequest\x1a&.orbita.engine.v1.ConfigSchemaResponse\x12W\n" +
	"\n" +
	"Initialize\x12#.orbita.engine.v1.InitializeRequest\x1a$.orbita.engine.v1.InitializeResponse\x12Z\n" +
	"\vHealthCheck\x12$.orbita.engine.v1.HealthCheckRequest\x1a%.orbita.engine.v1.HealthCheckResponse\x12Q\n" +
	"\bShutdown\x12!.orbita.engine.v1.ShutdownRequest\x1a\".orbita.engine.v1.ShutdownResponseBEZCgithub.com/felixgeelhaar/orbita/internal/engine/grpc/proto;enginepbb\x06proto3"

var (
	file_internal_engine_grpc_proto_engine_proto_rawDescOnce sync.Once
	file_internal_engine_grpc_proto_engine_proto_rawDescData []byte
)

func file_internal_engine_grpc_proto_engine_proto_rawDescGZIP() []byte {
	file_internal_engine_grpc_proto_engine_proto_rawDescOnce.Do(func() {
		file_internal_engine_grpc_proto_engine_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_engine_grpc_proto_engine_proto_rawDesc), len(file_internal_engine_grpc_proto_engine_proto_rawDesc)))
	})
	return file_internal_engine_grpc_proto_engine_proto_rawDescData
}

var file_internal_engine_grpc_proto_engine_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_internal_engine_grpc_proto_engine_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_internal_engine_grpc_proto_engine_proto_goTypes = []any{
	(EngineType)(0),               // 0: orbita.engine.v1.EngineType
	(*MetadataRequest)(nil),       // 1: orbita.engine.v1.MetadataRequest
	(*MetadataResponse)(nil),      // 2: orbita.engine.v1.MetadataResponse
	(*ConfigSchemaRequest)(nil),   // 3: orbita.engine.v1.ConfigSchemaRequest
	(*ConfigSchemaResponse)(nil),  // 4: orbita.engine.v1.ConfigSchemaResponse
	(*PropertySchema)(nil),        // 5: orbita.engine.v1.PropertySchema
	(*UIHints)(nil),               // 6: orbita.engine.v1.UIHints
	(*VisibilityCondition)(nil),   // 7: orbita.engine.v1.VisibilityCondition
	(*InitializeRequest)(nil),     // 8: orbita.engine.v1.InitializeRequest
	(*InitializeResponse)(nil),    // 9: orbita.engine.v1.InitializeResponse
	(*HealthCheckRequest)(nil),    // 10: orbita.engine.v1.HealthCheckRequest
	(*HealthCheckResponse)(nil),   // 11: orbita.engine.v1.HealthCheckResponse
	(*ShutdownRequest)(nil),       // 12: orbita.engine.v1.ShutdownRequest
	(*ShutdownResponse)(nil),      // 13: orbita.engine.v1.ShutdownResponse
	(*ExecutionContext)(nil),      // 14: orbita.engine.v1.ExecutionContext
	nil,                           // 15: orbita.engine.v1.ConfigSchemaResponse.PropertiesEntry
	(*structpb.Value)(nil),        // 16: google.protobuf.Value
	(*structpb.Struct)(nil),       // 17: google.protobuf.Struct
	(*timestamppb.Timestamp)(nil), // 18: google.protobuf.Timestamp
}
var file_internal_engine_grpc_proto_engine_proto_depIdxs = []int32{
	0,  // 0: orbita.engine.v1.MetadataResponse.type:type_name -> orbita.engine.v1.EngineType
	15, // 1: orbita.engine.v1.ConfigSchemaResponse.properties:type_name -> orbita.engine.v1.ConfigSchemaResponse.PropertiesEntry
	16, // 2: orbita.engine.v1.PropertySchema.default:type_name -> google.protobuf.Value
	16, // 3: orbita.engine.v1.PropertySchema.enum:type_name -> google.protobuf.Value
	5,  // 4: orbita.engine.v1.PropertySchema.items:type_name -> orbita.engine.v1.PropertySchema
	6,  // 5: orbita.engine.v1.PropertySchema.ui_hints:type_name -> orbita.engine.v1.UIHints
	7,  // 6: orbita.engine.v1.UIHints.visible:type_name -> orbita.engine.v1.VisibilityCondition
	16, // 7: orbita.engine.v1.VisibilityCondition.value:type_name -> google.protobuf.Value
	17, // 8: orbita.engine.v1.InitializeRequest.config:type_name -> google.protobuf.Struct
	17, // 9: orbita.engine.v1.HealthCheckResponse.details:type_name -> google.protobuf.Struct
	18, // 10: orbita.engine.v1.HealthCheckResponse.checked_at:type_name -> google.protobuf.Timestamp
	18, // 11: orbita.engine.v1.ExecutionContext.start_time:type_name -> google.protobuf.Timestamp
	5,  // 12: orbita.engine.v1.ConfigSchemaResponse.PropertiesEntry.value:type_name -> orbita.engine.v1.PropertySchema
	1,  // 13: orbita.engine.v1.Engine.Metadata:input_type -> orbita.engine.v1.MetadataRequest
	3,  // 14: orbita.engine.v1.Engine.ConfigSchema:input_type -> orbita.engine.v1.ConfigSchemaRequest
	8,  // 15: orbita.engine.v1.Engine.Initialize:input_type -> orbita.engine.v1.InitializeRequest
	10, // 16: orbita.engine.v1.Engine.HealthCheck:input_type -> orbita.engine.v1.HealthCheckRequest
	12, // 17: orbita.engine.v1.Engine.Shutdown:input_type -> orbita.engine.v1.ShutdownRequest
	2,  // 18: orbita.engine.v1.Engine.Metadata:output_type -> orbita.engine.v1.MetadataResponse
	4,  // 19: orbita.engine.v1.Engine.ConfigSchema:output_type -> orbita.engine.v1.ConfigSchemaResponse
	9,  // 20: orbita.engine.v1.Engine.Initialize:output_type -> orbita.engine.v1.InitializeResponse
	11, // 21: orbita.engine.v1.Engine.HealthCheck:output_type -> orbita.engine.v1.HealthCheckResponse
	13, // 22: orbita.engine.v1.Engine.Shutdown:output_type -> orbita.engine.v1.ShutdownResponse
	18, // [18:23] is the sub-list for method output_type
	13, // [13:18] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_internal_engine_grpc_proto_engine_proto_init() }
func file_internal_engine_grpc_proto_engine_proto_init() {
	if File_internal_engine_grpc_proto_engine_proto != nil {
		return
	}
	file_internal_engine_grpc_proto_engine_proto_msgTypes[4].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_engine_grpc_proto_engine_proto_rawDesc), len(file_internal_engine_grpc_proto_engine_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_engine_grpc_proto_engine_proto_goTypes,
		DependencyIndexes: file_internal_engine_grpc_proto_engine_proto_depIdxs,
		EnumInfos:         file_internal_engine_grpc_proto_engine_proto_enumTypes,
		MessageInfos:      file_internal_engine_grpc_proto_engine_proto_msgTypes,
	}.Build()
	File_internal_engine_grpc_proto_engine_proto = out.File
	file_internal_engine_grpc_proto_engine_proto_goTypes = nil
	file_internal_engine_grpc_proto_engine_proto_depIdxs = nil
}
