// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: internal/engine/grpc/proto/priority.proto

package enginepb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PriorityEngine_CalculatePriority_FullMethodName = "/orbita.engine.v1.PriorityEngine/CalculatePriority"
	PriorityEngine_BatchCalculate_FullMethodName    = "/orbita.engine.v1.PriorityEngine/BatchCalculate"
	PriorityEngine_ExplainFactors_FullMethodName    = "/orbita.engine.v1.PriorityEngine/ExplainFactors"
)

// PriorityEngineClient is the client API for PriorityEngine service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// PriorityEngine provides priority calculation capabilities.
type PriorityEngineClient interface {
	// CalculatePriority computes a priority score for a single item.
	CalculatePriority(ctx context.Context, in *PriorityRequest, opts ...grpc.CallOption) (*PriorityResponse, error)
	// BatchCalculate computes priority scores for multiple items.
	BatchCalculate(ctx context.Context, in *BatchPriorityRequest, opts ...grpc.CallOption) (*BatchPriorityResponse, error)
	// ExplainFactors provides detailed breakdown of score calculation.
	ExplainFactors(ctx context.Context, in *PriorityRequest, opts ...grpc.CallOption) (*PriorityExplanationResponse, error)
}

type priorityEngineClient struct {
	cc grpc.ClientConnInterface
}

func NewPriorityEngineClient(cc grpc.ClientConnInterface) PriorityEngineClient {
	return &priorityEngineClient{cc}
}

func (c *priorityEngineClient) CalculatePriority(ctx context.Context, in *PriorityRequest, opts ...grpc.CallOption) (*PriorityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PriorityResponse)
	err := c.cc.Invoke(ctx, PriorityEngine_CalculatePriority_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *priorityEngineClient) BatchCalculate(ctx context.Context, in *BatchPriorityRequest, opts ...grpc.CallOption) (*BatchPriorityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchPriorityResponse)
	err := c.cc.Invoke(ctx, PriorityEngine_BatchCalculate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *priorityEngineClient) ExplainFactors(ctx context.Context, in *PriorityRequest, opts ...grpc.CallOption) (*PriorityExplanationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PriorityExplanationResponse)
	err := c.cc.Invoke(ctx, PriorityEngine_ExplainFactors_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PriorityEngineServer is the server API for PriorityEngine service.
// All implementations must embed UnimplementedPriorityEngineServer
// for forward compatibility.
//
// PriorityEngine provides priority calculation capabilities.
type PriorityEngineServer interface {
	// CalculatePriority computes a priority score for a single item.
	CalculatePriority(context.Context, *PriorityRequest) (*PriorityResponse, error)
	// BatchCalculate computes priority scores for multiple items.
	BatchCalculate(context.Context, *BatchPriorityRequest) (*BatchPriorityResponse, error)
	// ExplainFactors provides detailed breakdown of score calculation.
	ExplainFactors(context.Context, *PriorityRequest) (*PriorityExplanationResponse, error)
	mustEmbedUnimplementedPriorityEngineServer()
}

// UnimplementedPriorityEngineServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPriorityEngineServer struct{}

func (UnimplementedPriorityEngineServer) CalculatePriority(context.Context, *PriorityRequest) (*PriorityResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CalculatePriority not implemented")
}
func (UnimplementedPriorityEngineServer) BatchCalculate(context.Context, *BatchPriorityRequest) (*BatchPriorityResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BatchCalculate not implemented")
}
func (UnimplementedPriorityEngineServer) ExplainFactors(context.Context, *PriorityRequest) (*PriorityExplanationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExplainFactors not implemented")
}
func (UnimplementedPriorityEngineServer) mustEmbedUnimplementedPriorityEngineServer() {}
func (UnimplementedPriorityEngineServer) testEmbeddedByValue()                        {}

// UnsafePriorityEngineServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PriorityEngineServer will
// result in compilation errors.
type UnsafePriorityEngineServer interface {
	mustEmbedUnimplementedPriorityEngineServer()
}

func RegisterPriorityEngineServer(s grpc.ServiceRegistrar, srv PriorityEngineServer) {
	// If the following call panics, it indicates UnimplementedPriorityEngineServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PriorityEngine_ServiceDesc, srv)
}

func _PriorityEngine_CalculatePriority_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PriorityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PriorityEngineServer).CalculatePriority(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PriorityEngine_CalculatePriority_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PriorityEngineServer).CalculatePriority(ctx, req.(*PriorityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PriorityEngine_BatchCalculate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchPriorityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PriorityEngineServer).BatchCalculate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PriorityEngine_BatchCalculate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PriorityEngineServer).BatchCalculate(ctx, req.(*BatchPriorityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PriorityEngine_ExplainFactors_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PriorityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PriorityEngineServer).ExplainFactors(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PriorityEngine_ExplainFactors_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PriorityEngineServer).ExplainFactors(ctx, req.(*PriorityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PriorityEngine_ServiceDesc is the grpc.ServiceDesc for PriorityEngine service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PriorityEngine_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "orbita.engine.v1.PriorityEngine",
	HandlerType: (*PriorityEngineServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CalculatePriority",
			Handler:    _PriorityEngine_CalculatePriority_Handler,
		},
		{
			MethodName: "BatchCalculate",
			Handler:    _PriorityEngine_BatchCalculate_Handler,
		},
		{
			MethodName: "ExplainFactors",
			Handler:    _PriorityEngine_ExplainFactors_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/engine/grpc/proto/priority.proto",
}
