// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: internal/engine/grpc/proto/priority.proto

package enginepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// UrgencyLevel categorizes priority.
type UrgencyLevel int32

const (
	UrgencyLevel_URGENCY_LEVEL_UNSPECIFIED UrgencyLevel = 0
	UrgencyLevel_URGENCY_LEVEL_CRITICAL    UrgencyLevel = 1
	UrgencyLevel_URGENCY_LEVEL_HIGH        UrgencyLevel = 2
	UrgencyLevel_URGENCY_LEVEL_MEDIUM      UrgencyLevel = 3
	UrgencyLevel_URGENCY_LEVEL_LOW         UrgencyLevel = 4
	UrgencyLevel_URGENCY_LEVEL_NONE        UrgencyLevel = 5
)

// Enum value maps for UrgencyLevel.
var (
	UrgencyLevel_name = map[int32]string{
		0: "URGENCY_LEVEL_UNSPECIFIED",
		1: "URGENCY_LEVEL_CRITICAL",
		2: "URGENCY_LEVEL_HIGH",
		3: "URGENCY_LEVEL_MEDIUM",
		4: "URGENCY_LEVEL_LOW",
		5: "URGENCY_LEVEL_NONE",
	}
	UrgencyLevel_value = map[string]int32{
		"URGENCY_LEVEL_UNSPECIFIED": 0,
		"URGENCY_LEVEL_CRITICAL":    1,
		"URGENCY_LEVEL_HIGH":        2,
		"URGENCY_LEVEL_MEDIUM":      3,
		"URGENCY_LEVEL_LOW":         4,
		"URGENCY_LEVEL_NONE":        5,
	}
)

func (x UrgencyLevel) Enum() *UrgencyLevel {
	p := new(UrgencyLevel)
	*p = x
	return p
}

func (x UrgencyLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UrgencyLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_engine_grpc_proto_priority_proto_enumTypes[0].Descriptor()
}

func (UrgencyLevel) Type() protoreflect.EnumType {
	return &file_internal_engine_grpc_proto_priority_proto_enumTypes[0]
}

func (x UrgencyLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UrgencyLevel.Descriptor instead.
func (UrgencyLevel) EnumDescriptor() ([]byte, []int) {
	return file_internal_engine_grpc_proto_priority_proto_rawDescGZIP(), []int{0}
}

// PriorityRequest contains signals for priority calculation.
type PriorityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Context       *ExecutionContext      `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	Input         *PriorityInput         `protobuf:"bytes,2,opt,name=input,proto3" json:"input,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PriorityRequest) Reset() {
	*x = PriorityRequest{}
	mi := &file_internal_engine_grpc_proto_priority_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PriorityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PriorityRequest) ProtoMessage() {}

func (x *PriorityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_engine_grpc_proto_priority_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PriorityRequest.ProtoReflect.Descriptor instead.
func (*PriorityRequest) Descriptor() ([]byte, []int) {
	return file_internal_engine_grpc_proto_priority_proto_rawDescGZIP(), []int{0}
}

func (x *PriorityRequest) GetContext() *ExecutionContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *PriorityRequest) GetInput() *PriorityInput {
	if x != nil {
		return x.Input
	}
	return nil
}

// PriorityInput contains the signals used to calculate priority.
type PriorityInput struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Priority       int32                  `protobuf:"varint,2,opt,name=priority,proto3" json:"priority,omitempty"`
	DueDate        *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=due_date,json=dueDate,proto3" json:"due_date,omitempty"`
	Duration       *durationpb.Duration   `protobuf:"bytes,4,opt,name=duration,proto3" json:"duration,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	StreakRisk     float64                `protobuf:"fixed64,6,opt,name=streak_risk,json=streakRisk,proto3" json:"streak_risk,omitempty"`
	MeetingCadence float64                `protobuf:"fixed64,7,opt,name=meeting_cadence,json=meetingCadence,proto3" json:"meeting_cadence,omitempty"`
	Tags           []string               `protobuf:"bytes,8,rep,name=tags,proto3" json:"tags,omitempty"`
	Context        *PriorityContext       `protobuf:"bytes,9,opt,name=context,proto3" json:"context,omitempty"`
	CustomSignals  map[string]float64     `protobuf:"bytes,10,rep,name=custom_signals,json=customSignals,proto3" json:"custom_signals,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PriorityInput) Reset() {
	*x = PriorityInput{}
	mi := &file_internal_engine_grpc_proto_priority_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PriorityInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PriorityInput) ProtoMessage() {}

func (x *PriorityInput) ProtoReflect() protoreflect.Message {
	mi := &file_internal_engine_grpc_proto_priority_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PriorityInput.ProtoReflect.Descriptor instead.
func (*PriorityInput) Descriptor() ([]byte, []int) {
	return file_internal_engine_grpc_proto_priority_proto_rawDescGZIP(), []int{1}
}

func (x *PriorityInput) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PriorityInput) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *PriorityInput) GetDueDate() *timestamppb.Timestamp {
	if x != nil {
		return x.DueDate
	}
	return nil
}

func (x *PriorityInput) GetDuration() *durationpb.Duration {
	if x != nil {
		return x.Duration
	}
	return nil
}

func (x *PriorityInput) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *PriorityInput) GetStreakRisk() float64 {
	if x != nil {
		return x.StreakRisk
	}
	return 0
}

func (x *PriorityInput) GetMeetingCadence() float64 {
	if x != nil {
		return x.MeetingCadence
	}
	return 0
}

func (x *PriorityInput) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *PriorityInput) GetContext() *PriorityContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *PriorityInput) GetCustomSignals() map[string]float64 {
	if x != nil {
		return x.CustomSignals
	}
	return nil
}

// PriorityContext provides situational information.
type PriorityContext struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	TimeOfDay          string                 `protobuf:"bytes,1,opt,name=time_of_day,json=timeOfDay,proto3" json:"time_of_day,omitempty"`
	DayOfWeek          string                 `protobuf:"bytes,2,opt,name=day_of_week,json=dayOfWeek,proto3" json:"day_of_week,omitempty"`
	EnergyLevel        int32                  `protobuf:"varint,3,opt,name=energy_level,json=energyLevel,proto3" json:"energy_level,omitempty"`
	FocusMode          bool                   `protobuf:"varint,4,opt,name=focus_mode,json=focusMode,proto3" json:"focus_mode,omitempty"`
	RelatedCompletions int32                  `protobuf:"varint,5,opt,name=related_completions,json=relatedCompletions,proto3" json:"related_completions,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *PriorityContext) Reset() {
	*x = PriorityContext{}
	mi := &file_internal_engine_grpc_proto_priority_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PriorityContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PriorityContext) ProtoMessage() {}

func (x *PriorityContext) ProtoReflect() protoreflect.Message {
	mi := &file_internal_engine_grpc_proto_priority_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PriorityContext.ProtoReflect.Descriptor instead.
func (*PriorityContext) Descriptor() ([]byte, []int) {
	return file_internal_engine_grpc_proto_priority_proto_rawDescGZIP(), []int{2}
}

func (x *PriorityContext) GetTimeOfDay() string {
	if x != nil {
		return x.TimeOfDay
	}
	return ""
}

func (x *PriorityContext) GetDayOfWeek() string {
	if x != nil {
		return x.DayOfWeek
	}
	return ""
}

func (x *PriorityContext) GetEnergyLevel() int32 {
	if x != nil {
		return x.EnergyLevel
	}
	return 0
}

func (x *PriorityContext) GetFocusMode() bool {
	if x != nil {
		return x.FocusMode
	}
	return false
}

func (x *PriorityContext) GetRelatedCompletions() int32 {
	if x != nil {
		return x.RelatedCompletions
	}
	return 0
}

// PriorityResponse contains the calculated priority.
type PriorityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Output        *PriorityOutput        `protobuf:"bytes,1,opt,name=output,proto3" json:"output,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PriorityResponse) Reset() {
	*x = PriorityResponse{}
	mi := &file_internal_engine_grpc_proto_priority_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PriorityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PriorityResponse) ProtoMessage() {}

func (x *PriorityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_engine_grpc_proto_priority_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PriorityResponse.ProtoReflect.Descriptor instead.
func (*PriorityResponse) Descriptor() ([]byte, []int) {
	return file_internal_engine_grpc_proto_priority_proto_rawDescGZIP(), []int{3}
}

func (x *PriorityResponse) GetOutput() *PriorityOutput {
	if x != nil {
		return x.Output
	}
	return nil
}

// PriorityOutput contains the calculated priority score.
type PriorityOutput struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Score           float64                `protobuf:"fixed64,2,opt,name=score,proto3" json:"score,omitempty"`
	NormalizedScore float64                `protobuf:"fixed64,3,opt,name=normalized_score,json=normalizedScore,proto3" json:"normalized_score,omitempty"`
	Rank            int32                  `protobuf:"varint,4,opt,name=rank,proto3" json:"rank,omitempty"`
	Explanation     string                 `protobuf:"bytes,5,opt,name=explanation,proto3" json:"explanation,omitempty"`
	Factors         map[string]float64     `protobuf:"bytes,6,rep,name=factors,proto3" json:"factors,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
	Urgency         UrgencyLevel           `protobuf:"varint,7,opt,name=urgency,proto3,enum=orbita.engine.v1.UrgencyLevel" json:"urgency,omitempty"`
	SuggestedAction string                 `protobuf:"bytes,8,opt,name=suggested_action,json=suggestedAction,proto3" json:"suggested_action,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PriorityOutput) Reset() {
	*x = PriorityOutput{}
	mi := &file_internal_engine_grpc_proto_priority_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PriorityOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PriorityOutput) ProtoMessage() {}

func (x *PriorityOutput) ProtoReflect() protoreflect.Message {
	mi := &file_internal_engine_grpc_proto_priority_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PriorityOutput.ProtoReflect.Descriptor instead.
func (*PriorityOutput) Descriptor() ([]byte, []int) {
	return file_internal_engine_grpc_proto_priority_proto_rawDescGZIP(), []int{4}
}

func (x *PriorityOutput) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PriorityOutput) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *PriorityOutput) GetNormalizedScore() float64 {
	if x != nil {
		return x.NormalizedScore
	}
	return 0
}

func (x *PriorityOutput) GetRank() int32 {
	if x != nil {
		return x.Rank
	}
	return 0
}

func (x *PriorityOutput) GetExplanation() string {
	if x != nil {
		return x.Explanation
	}
	return ""
}

func (x *PriorityOutput) GetFactors() map[string]float64 {
	if x != nil {
		return x.Factors
	}
	return nil
}

func (x *PriorityOutput) GetUrgency() UrgencyLevel {
	if x != nil {
		return x.Urgency
	}
	return UrgencyLevel_URGENCY_LEVEL_UNSPECIFIED
}

func (x *PriorityOutput) GetSuggestedAction() string {
	if x != nil {
		return x.SuggestedAction
	}
	return ""
}

// BatchPriorityRequest contains multiple items to score.
type BatchPriorityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Context       *ExecutionContext      `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	Inputs        []*PriorityInput       `protobuf:"bytes,2,rep,name=inputs,proto3" json:"inputs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchPriorityRequest) Reset() {
	*x = BatchPriorityRequest{}
	mi := &file_internal_engine_grpc_proto_priority_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchPriorityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchPriorityRequest) ProtoMessage() {}

func (x *BatchPriorityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_engine_grpc_proto_priority_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchPriorityRequest.ProtoReflect.Descriptor instead.
func (*BatchPriorityRequest) Descriptor() ([]byte, []int) {
	return file_internal_engine_grpc_proto_priority_proto_rawDescGZIP(), []int{5}
}

func (x *BatchPriorityRequest) GetContext() *ExecutionContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *BatchPriorityRequest) GetInputs() []*PriorityInput {
	if x != nil {
		return x.Inputs
	}
	return nil
}

// BatchPriorityResponse contains scores for all items.
type BatchPriorityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Outputs       []*PriorityOutput      `protobuf:"bytes,1,rep,name=outputs,proto3" json:"outputs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchPriorityResponse) Reset() {
	*x = BatchPriorityResponse{}
	mi := &file_internal_engine_grpc_proto_priority_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchPriorityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchPriorityResponse) ProtoMessage() {}

func (x *BatchPriorityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_engine_grpc_proto_priority_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchPriorityResponse.ProtoReflect.Descriptor instead.
func (*BatchPriorityResponse) Descriptor() ([]byte, []int) {
	return file_internal_engine_grpc_proto_priority_proto_rawDescGZIP(), []int{6}
}

func (x *BatchPriorityResponse) GetOutputs() []*PriorityOutput {
	if x != nil {
		return x.Outputs
	}
	return nil
}

// PriorityExplanationResponse provides detailed breakdown.
type PriorityExplanationResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TotalScore      float64                `protobuf:"fixed64,2,opt,name=total_score,json=totalScore,proto3" json:"total_score,omitempty"`
	Factors         []*FactorBreakdown     `protobuf:"bytes,3,rep,name=factors,proto3" json:"factors,omitempty"`
	Algorithm       string                 `protobuf:"bytes,4,opt,name=algorithm,proto3" json:"algorithm,omitempty"`
	Weights         map[string]float64     `protobuf:"bytes,5,rep,name=weights,proto3" json:"weights,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
	Recommendations []string               `protobuf:"bytes,6,rep,name=recommendations,proto3" json:"recommendations,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PriorityExplanationResponse) Reset() {
	*x = PriorityExplanationResponse{}
	mi := &file_internal_engine_grpc_proto_priority_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PriorityExplanationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PriorityExplanationResponse) ProtoMessage() {}

func (x *PriorityExplanationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_engine_grpc_proto_priority_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PriorityExplanationResponse.ProtoReflect.Descriptor instead.
func (*PriorityExplanationResponse) Descriptor() ([]byte, []int) {
	return file_internal_engine_grpc_proto_priority_proto_rawDescGZIP(), []int{7}
}

func (x *PriorityExplanationResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PriorityExplanationResponse) GetTotalScore() float64 {
	if x != nil {
		return x.TotalScore
	}
	return 0
}

func (x *PriorityExplanationResponse) GetFactors() []*FactorBreakdown {
	if x != nil {
		return x.Factors
	}
	return nil
}

func (x *PriorityExplanationResponse) GetAlgorithm() string {
	if x != nil {
		return x.Algorithm
	}
	return ""
}

func (x *PriorityExplanationResponse) GetWeights() map[string]float64 {
	if x != nil {
		return x.Weights
	}
	return nil
}

func (x *PriorityExplanationResponse) GetRecommendations() []string {
	if x != nil {
		return x.Recommendations
	}
	return nil
}

// FactorBreakdown shows how a factor contributed.
type FactorBreakdown struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	RawValue      float64                `protobuf:"fixed64,2,opt,name=raw_value,json=rawValue,proto3" json:"raw_value,omitempty"`
	Weight        float64                `protobuf:"fixed64,3,opt,name=weight,proto3" json:"weight,omitempty"`
	WeightedValue float64                `protobuf:"fixed64,4,opt,name=weighted_value,json=weightedValue,proto3" json:"weighted_value,omitempty"`
	Contribution  float64                `protobuf:"fixed64,5,opt,name=contribution,proto3" json:"contribution,omitempty"`
	Description   string                 `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FactorBreakdown) Reset() {
	*x = FactorBreakdown{}
	mi := &file_internal_engine_grpc_proto_priority_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FactorBreakdown) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FactorBreakdown) ProtoMessage() {}

func (x *FactorBreakdown) ProtoReflect() protoreflect.Message {
	mi := &file_internal_engine_grpc_proto_priority_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FactorBreakdown.ProtoReflect.Descriptor instead.
func (*FactorBreakdown) Descriptor() ([]byte, []int) {
	return file_internal_engine_grpc_proto_priority_proto_rawDescGZIP(), []int{8}
}

func (x *FactorBreakdown) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FactorBreakdown) GetRawValue() float64 {
	if x != nil {
		return x.RawValue
	}
	return 0
}

func (x *FactorBreakdown) GetWeight() float64 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *FactorBreakdown) GetWeightedValue() float64 {
	if x != nil {
		return x.WeightedValue
	}
	return 0
}

func (x *FactorBreakdown) GetContribution() float64 {
	if x != nil {
		return x.Contribution
	}
	return 0
}

func (x *FactorBreakdown) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

var File_internal_engine_grpc_proto_priority_proto protoreflect.FileDescriptor

const file_internal_engine_grpc_proto_priority_proto_rawDesc = "" +
	"\n" +
	")internal/engine/grpc/proto/priority.proto\x12\x10orbita.engine.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/duration.proto\x1a'internal/engine/grpc/proto/engine.proto\"\x86\x01\n" +
	"\x0fPriorityRequest\x12<\n" +
	"\acontext\x18\x01 \x01(\v2\".orbita.engine.v1.ExecutionContextR\acontext\x125\n" +
	"\x05input\x18\x02 \x01(\v2\x1f.orbita.engine.v1.PriorityInputR\x05input\"\x9c\x04\n" +
	"\rPriorityInput\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\bpriority\x18\x02 \x01(\x05R\bpriority\x125\n" +
	"\bdue_date\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\adueDate\x125\n" +
	"\bduration\x18\x04 \x01(\v2\x19.google.protobuf.DurationR\bduration\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x1f\n" +
	"\vstreak_risk\x18\x06 \x01(\x01R\n" +
	"streakRisk\x12'\n" +
	"\x0fmeeting_cadence\x18\a \x01(\x01R\x0emeetingCadence\x12\x12\n" +
	"\x04tags\x18\b \x03(\tR\x04tags\x12;\n" +
	"\acontext\x18\t \x01(\v2!.orbita.engine.v1.PriorityContextR\acontext\x12Y\n" +
	"\x0ecustom_signals\x18\n" +
	" \x03(\v22.orbita.engine.v1.PriorityInput.CustomSignalsEntryR\rcustomSignals\x1a@\n" +
	"\x12CustomSignalsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01\"\xc4\x01\n" +
	"\x0fPriorityContext\x12\x1e\n" +
	"\vtime_of_day\x18\x01 \x01(\tR\ttimeOfDay\x12\x1e\n" +
	"\vday_of_week\x18\x02 \x01(\tR\tdayOfWeek\x12!\n" +
	"\fenergy_level\x18\x03 \x01(\x05R\venergyLevel\x12\x1d\n" +
	"\n" +
	"focus_mode\x18\x04 \x01(\bR\tfocusMode\x12/\n" +
	"\x13related_completions\x18\x05 \x01(\x05R\x12relatedCompletions\"L\n" +
	"\x10PriorityResponse\x128\n" +
	"\x06output\x18\x01 \x01(\v2 .orbita.engine.v1.PriorityOutputR\x06output\"\x81\x03\n" +
	"\x0ePriorityOutput\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05score\x18\x02 \x01(\x01R\x05score\x12)\n" +
	"\x10normalized_score\x18\x03 \x01(\x01R\x0fnormalizedScore\x12\x12\n" +
	"\x04rank\x18\x04 \x01(\x05R\x04rank\x12 \n" +
	"\vexplanation\x18\x05 \x01(\tR\vexplanation\x12G\n" +
	"\afactors\x18\x06 \x03(\v2-.orbita.engine.v1.PriorityOutput.FactorsEntryR\afactors\x128\n" +
	"\aurgency\x18\a \x01(\x0e2\x1e.orbita.engine.v1.UrgencyLevelR\aurgency\x12)\n" +
	"\x10suggested_action\x18\b \x01(\tR\x0fsuggestedAction\x1a:\n" +
	"\fFactorsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01\"\x8d\x01\n" +
	"\x14BatchPriorityRequest\x12<\n" +
	"\acontext\x18\x01 \x01(\v2\".orbita.engine.v1.ExecutionContextR\acontext\x127\n" +
	"\x06inputs\x18\x02 \x03(\v2\x1f.orbita.engine.v1.PriorityInputR\x06inputs\"S\n" +
	"\x15BatchPriorityResponse\x12:\n" +
	"\aoutputs\x18\x01 \x03(\v2 .orbita.engine.v1.PriorityOutputR\aoutputs\"\xe5\x02\n" +
	"\x1bPriorityExplanationResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vtotal_score\x18\x02 \x01(\x01R\n" +
	"totalScore\x12;\n" +
	"\afactors\x18\x03 \x03(\v2!.orbita.engine.v1.FactorBreakdownR\afactors\x12\x1c\n" +
	"\talgorithm\x18\x04 \x01(\tR\talgorithm\x12T\n" +
	"\aweights\x18\x05 \x03(\v2:.orbita.engine.v1.PriorityExplanationResponse.WeightsEntryR\aweights\x12(\n" +
	"\x0frecommendations\x18\x06 \x03(\tR\x0frecommendations\x1a:\n" +
	"\fWeightsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01\"\xc7\x01\n" +
	"\x0fFactorBreakdown\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1b\n" +
	"\traw_value\x18\x02 \x01(\x01R\brawValue\x12\x16\n" +
	"\x06weight\x18\x03 \x01(\x01R\x06weight\x12%\n" +
	"\x0eweighted_value\x18\x04 \x01(\x01R\rweightedValue\x12\"\n" +
	"\fcontribution\x18\x05 \x01(\x01R\fcontribution\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription*\xaa\x01\n" +
	"\fUrgencyLevel\x12\x1d\n" +
	"\x19URGENCY_LEVEL_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16URGENCY_LEVEL_CRITICAL\x10\x01\x12\x16\n" +
	"\x12URGENCY_LEVEL_HIGH\x10\x02\x12\x18\n" +
	"\x14URGENCY_LEVEL_MEDIUM\x10\x03\x12\x15\n" +
	"\x11URGENCY_LEVEL_LOW\x10\x04\x12\x16\n" +
	"\x12URGENCY_LEVEL_NONE\x10\x052\xb3\x02\n" +
	"\x0ePriorityEngine\x12Z\n" +
	"\x11CalculatePriority\x12!.orbita.engine.v1.PriorityRequest\x1a\".orbita.engine.v1.PriorityResponse\x12a\n" +
	"\x0eBatchCalculate\x12&.orbita.engine.v1.BatchPriorityRequest\x1a'.orbita.engine.v1.BatchPriorityResponse\x12b\n" +
	"\x0eExplainFactors\x12!.orbita.engine.v1.PriorityRequest\x1a-.orbita.engine.v1.PriorityExplanationResponseBEZCgithub.com/felixgeelhaar/orbita/internal/engine/grpc/proto;enginepbb\x06proto3"

var (
	file_internal_engine_grpc_proto_priority_proto_rawDescOnce sync.Once
	file_internal_engine_grpc_proto_priority_proto_rawDescData []byte
)

func file_internal_engine_grpc_proto_priority_proto_rawDescGZIP() []byte {
	file_internal_engine_grpc_proto_priority_proto_rawDescOnce.Do(func() {
		file_internal_engine_grpc_proto_priority_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_engine_grpc_proto_priority_proto_rawDesc), len(file_internal_engine_grpc_proto_priority_proto_rawDesc)))
	})
	return file_internal_engine_grpc_proto_priority_proto_rawDescData
}

var file_internal_engine_grpc_proto_priority_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_internal_engine_grpc_proto_priority_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_internal_engine_grpc_proto_priority_proto_goTypes = []any{
	(UrgencyLevel)(0),                   // 0: orbita.engine.v1.UrgencyLevel
	(*PriorityRequest)(nil),             // 1: orbita.engine.v1.PriorityRequest
	(*PriorityInput)(nil),               // 2: orbita.engine.v1.PriorityInput
	(*PriorityContext)(nil),             // 3: orbita.engine.v1.PriorityContext
	(*PriorityResponse)(nil),            // 4: orbita.engine.v1.PriorityResponse
	(*PriorityOutput)(nil),              // 5: orbita.engine.v1.PriorityOutput
	(*BatchPriorityRequest)(nil),        // 6: orbita.engine.v1.BatchPriorityRequest
	(*BatchPriorityResponse)(nil),       // 7: orbita.engine.v1.BatchPriorityResponse
	(*PriorityExplanationResponse)(nil), // 8: orbita.engine.v1.PriorityExplanationResponse
	(*FactorBreakdown)(nil),             // 9: orbita.engine.v1.FactorBreakdown
	nil,                                 // 10: orbita.engine.v1.PriorityInput.CustomSignalsEntry
	nil,                                 // 11: orbita.engine.v1.PriorityOutput.FactorsEntry
	nil,                                 // 12: orbita.engine.v1.PriorityExplanationResponse.WeightsEntry
	(*ExecutionContext)(nil),            // 13: orbita.engine.v1.ExecutionContext
	(*timestamppb.Timestamp)(nil),       // 14: google.protobuf.Timestamp
	(*durationpb.Duration)(nil),         // 15: google.protobuf.Duration
}
var file_internal_engine_grpc_proto_priority_proto_depIdxs = []int32{
	13, // 0: orbita.engine.v1.PriorityRequest.context:type_name -> orbita.engine.v1.ExecutionContext
	2,  // 1: orbita.engine.v1.PriorityRequest.input:type_name -> orbita.engine.v1.PriorityInput
	14, // 2: orbita.engine.v1.PriorityInput.due_date:type_name -> google.protobuf.Timestamp
	15, // 3: orbita.engine.v1.PriorityInput.duration:type_name -> google.protobuf.Duration
	14, // 4: orbita.engine.v1.PriorityInput.created_at:type_name -> google.protobuf.Timestamp
	3,  // 5: orbita.engine.v1.PriorityInput.context:type_name -> orbita.engine.v1.PriorityContext
	10, // 6: orbita.engine.v1.PriorityInput.custom_signals:type_name -> orbita.engine.v1.PriorityInput.CustomSignalsEntry
	5,  // 7: orbita.engine.v1.PriorityResponse.output:type_name -> orbita.engine.v1.PriorityOutput
	11, // 8: orbita.engine.v1.PriorityOutput.factors:type_name -> orbita.engine.v1.PriorityOutput.FactorsEntry
	0,  // 9: orbita.engine.v1.PriorityOutput.urgency:type_name -> orbita.engine.v1.UrgencyLevel
	13, // 10: orbita.engine.v1.BatchPriorityRequest.context:type_name -> orbita.engine.v1.ExecutionContext
	2,  // 11: orbita.engine.v1.BatchPriorityRequest.inputs:type_name -> orbita.engine.v1.PriorityInput
	5,  // 12: orbita.engine.v1.BatchPriorityResponse.outputs:type_name -> orbita.engine.v1.PriorityOutput
	9,  // 13: orbita.engine.v1.PriorityExplanationResponse.factors:type_name -> orbita.engine.v1.FactorBreakdown
	12, // 14: orbita.engine.v1.PriorityExplanationResponse.weights:type_name -> orbita.engine.v1.PriorityExplanationResponse.WeightsEntry
	1,  // 15: orbita.engine.v1.PriorityEngine.CalculatePriority:input_type -> orbita.engine.v1.PriorityRequest
	6,  // 16: orbita.engine.v1.PriorityEngine.BatchCalculate:input_type -> orbita.engine.v1.BatchPriorityRequest
	1,  // 17: orbita.engine.v1.PriorityEngine.ExplainFactors:input_type -> orbita.engine.v1.PriorityRequest
	4,  // 18: orbita.engine.v1.PriorityEngine.CalculatePriority:output_type -> orbita.engine.v1.PriorityResponse
	7,  // 19: orbita.engine.v1.PriorityEngine.BatchCalculate:output_type -> orbita.engine.v1.BatchPriorityResponse
	8,  // 20: orbita.engine.v1.PriorityEngine.ExplainFactors:output_type -> orbita.engine.v1.PriorityExplanationResponse
	18, // [18:21] is the sub-list for method output_type
	15, // [15:18] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_internal_engine_grpc_proto_priority_proto_init() }
func file_internal_engine_grpc_proto_priority_proto_init() {
	if File_internal_engine_grpc_proto_priority_proto != nil {
		return
	}
	file_internal_engine_grpc_proto_engine_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_engine_grpc_proto_priority_proto_rawDesc), len(file_internal_engine_grpc_proto_priority_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_engine_grpc_proto_priority_proto_goTypes,
		DependencyIndexes: file_internal_engine_grpc_proto_priority_proto_depIdxs,
		EnumInfos:         file_internal_engine_grpc_proto_priority_proto_enumTypes,
		MessageInfos:      file_internal_engine_grpc_proto_priority_proto_msgTypes,
	}.Build()
	File_internal_engine_grpc_proto_priority_proto = out.File
	file_internal_engine_grpc_proto_priority_proto_goTypes = nil
	file_internal_engine_grpc_proto_priority_proto_depIdxs = nil
}
