// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: internal/engine/grpc/proto/scheduler.proto

package enginepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ScheduleTasksRequest contains parameters for scheduling tasks.
type ScheduleTasksRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Context        *ExecutionContext      `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	Date           *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"`
	Tasks          []*SchedulableTask     `protobuf:"bytes,3,rep,name=tasks,proto3" json:"tasks,omitempty"`
	ExistingBlocks []*ExistingBlock       `protobuf:"bytes,4,rep,name=existing_blocks,json=existingBlocks,proto3" json:"existing_blocks,omitempty"`
	WorkingHours   *WorkingHours          `protobuf:"bytes,5,opt,name=working_hours,json=workingHours,proto3" json:"working_hours,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ScheduleTasksRequest) Reset() {
	*x = ScheduleTasksRequest{}
	mi := &file_internal_engine_grpc_proto_scheduler_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScheduleTasksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScheduleTasksRequest) ProtoMessage() {}

func (x *ScheduleTasksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_engine_grpc_proto_scheduler_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScheduleTasksRequest.ProtoReflect.Descriptor instead.
func (*ScheduleTasksRequest) Descriptor() ([]byte, []int) {
	return file_internal_engine_grpc_proto_scheduler_proto_rawDescGZIP(), []int{0}
}

func (x *ScheduleTasksRequest) GetContext() *ExecutionContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *ScheduleTasksRequest) GetDate() *timestamppb.Timestamp {
	if x != nil {
		return x.Date
	}
	return nil
}

func (x *ScheduleTasksRequest) GetTasks() []*SchedulableTask {
	if x != nil {
		return x.Tasks
	}
	return nil
}

func (x *ScheduleTasksRequest) GetExistingBlocks() []*ExistingBlock {
	if x != nil {
		return x.ExistingBlocks
	}
	return nil
}

func (x *ScheduleTasksRequest) GetWorkingHours() *WorkingHours {
	if x != nil {
		return x.WorkingHours
	}
	return nil
}

// SchedulableTask represents a task to be scheduled.
type SchedulableTask struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Priority      int32                  `protobuf:"varint,3,opt,name=priority,proto3" json:"priority,omitempty"`
	Duration      *durationpb.Duration   `protobuf:"bytes,4,opt,name=duration,proto3" json:"duration,omitempty"`
	DueDate       *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=due_date,json=dueDate,proto3" json:"due_date,omitempty"`
	BlockType     string                 `protobuf:"bytes,6,opt,name=block_type,json=blockType,proto3" json:"block_type,omitempty"`
	Constraints   []*Constraint          `protobuf:"bytes,7,rep,name=constraints,proto3" json:"constraints,omitempty"`
	Metadata      *structpb.Struct       `protobuf:"bytes,8,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SchedulableTask) Reset() {
	*x = SchedulableTask{}
	mi := &file_internal_engine_grpc_proto_scheduler_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SchedulableTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SchedulableTask) ProtoMessage() {}

func (x *SchedulableTask) ProtoReflect() protoreflect.Message {
	mi := &file_internal_engine_grpc_proto_scheduler_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SchedulableTask.ProtoReflect.Descriptor instead.
func (*SchedulableTask) Descriptor() ([]byte, []int) {
	return file_internal_engine_grpc_proto_scheduler_proto_rawDescGZIP(), []int{1}
}

func (x *SchedulableTask) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SchedulableTask) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *SchedulableTask) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *SchedulableTask) GetDuration() *durationpb.Duration {
	if x != nil {
		return x.Duration
	}
	return nil
}

func (x *SchedulableTask) GetDueDate() *timestamppb.Timestamp {
	if x != nil {
		return x.DueDate
	}
	return nil
}

func (x *SchedulableTask) GetBlockType() string {
	if x != nil {
		return x.BlockType
	}
	return ""
}

func (x *SchedulableTask) GetConstraints() []*Constraint {
	if x != nil {
		return x.Constraints
	}
	return nil
}

func (x *SchedulableTask) GetMetadata() *structpb.Struct {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// Constraint represents a scheduling constraint.
type Constraint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Start         *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=start,proto3" json:"start,omitempty"`
	End           *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=end,proto3" json:"end,omitempty"`
	ReferenceId   string                 `protobuf:"bytes,4,opt,name=reference_id,json=referenceId,proto3" json:"reference_id,omitempty"`
	Flexible      bool                   `protobuf:"varint,5,opt,name=flexible,proto3" json:"flexible,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Constraint) Reset() {
	*x = Constraint{}
	mi := &file_internal_engine_grpc_proto_scheduler_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Constraint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Constraint) ProtoMessage() {}

func (x *Constraint) ProtoReflect() protoreflect.Message {
	mi := &file_internal_engine_grpc_proto_scheduler_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Constraint.ProtoReflect.Descriptor instead.
func (*Constraint) Descriptor() ([]byte, []int) {
	return file_internal_engine_grpc_proto_scheduler_proto_rawDescGZIP(), []int{2}
}

func (x *Constraint) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Constraint) GetStart() *timestamppb.Timestamp {
	if x != nil {
		return x.Start
	}
	return nil
}

func (x *Constraint) GetEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.End
	}
	return nil
}

func (x *Constraint) GetReferenceId() string {
	if x != nil {
		return x.ReferenceId
	}
	return ""
}

func (x *Constraint) GetFlexible() bool {
	if x != nil {
		return x.Flexible
	}
	return false
}

// ExistingBlock represents a block already on the schedule.
type ExistingBlock struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Start         *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=start,proto3" json:"start,omitempty"`
	End           *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=end,proto3" json:"end,omitempty"`
	Title         string                 `protobuf:"bytes,5,opt,name=title,proto3" json:"title,omitempty"`
	Immovable     bool                   `protobuf:"varint,6,opt,name=immovable,proto3" json:"immovable,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExistingBlock) Reset() {
	*x = ExistingBlock{}
	mi := &file_internal_engine_grpc_proto_scheduler_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExistingBlock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExistingBlock) ProtoMessage() {}

func (x *ExistingBlock) ProtoReflect() protoreflect.Message {
	mi := &file_internal_engine_grpc_proto_scheduler_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExistingBlock.ProtoReflect.Descriptor instead.
func (*ExistingBlock) Descriptor() ([]byte, []int) {
	return file_internal_engine_grpc_proto_scheduler_proto_rawDescGZIP(), []int{3}
}

func (x *ExistingBlock) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ExistingBlock) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ExistingBlock) GetStart() *timestamppb.Timestamp {
	if x != nil {
		return x.Start
	}
	return nil
}

func (x *ExistingBlock) GetEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.End
	}
	return nil
}

func (x *ExistingBlock) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ExistingBlock) GetImmovable() bool {
	if x != nil {
		return x.Immovable
	}
	return false
}

// WorkingHours defines available scheduling windows.
type WorkingHours struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Start         *durationpb.Duration   `protobuf:"bytes,1,opt,name=start,proto3" json:"start,omitempty"`
	End           *durationpb.Duration   `protobuf:"bytes,2,opt,name=end,proto3" json:"end,omitempty"`
	Breaks        []*TimeWindow          `protobuf:"bytes,3,rep,name=breaks,proto3" json:"breaks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkingHours) Reset() {
	*x = WorkingHours{}
	mi := &file_internal_engine_grpc_proto_scheduler_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkingHours) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkingHours) ProtoMessage() {}

func (x *WorkingHours) ProtoReflect() protoreflect.Message {
	mi := &file_internal_engine_grpc_proto_scheduler_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkingHours.ProtoReflect.Descriptor instead.
func (*WorkingHours) Descriptor() ([]byte, []int) {
	return file_internal_engine_grpc_proto_scheduler_proto_rawDescGZIP(), []int{4}
}

func (x *WorkingHours) GetStart() *durationpb.Duration {
	if x != nil {
		return x.Start
	}
	return nil
}

func (x *WorkingHours) GetEnd() *durationpb.Duration {
	if x != nil {
		return x.End
	}
	return nil
}

func (x *WorkingHours) GetBreaks() []*TimeWindow {
	if x != nil {
		return x.Breaks
	}
	return nil
}

// TimeWindow represents a time range.
type TimeWindow struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Start         *durationpb.Duration   `protobuf:"bytes,1,opt,name=start,proto3" json:"start,omitempty"`
	End           *durationpb.Duration   `protobuf:"bytes,2,opt,name=end,proto3" json:"end,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimeWindow) Reset() {
	*x = TimeWindow{}
	mi := &file_internal_engine_grpc_proto_scheduler_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimeWindow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeWindow) ProtoMessage() {}

func (x *TimeWindow) ProtoReflect() protoreflect.Message {
	mi := &file_internal_engine_grpc_proto_scheduler_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeWindow.ProtoReflect.Descriptor instead.
func (*TimeWindow) Descriptor() ([]byte, []int) {
	return file_internal_engine_grpc_proto_scheduler_proto_rawDescGZIP(), []int{5}
}

func (x *TimeWindow) GetStart() *durationpb.Duration {
	if x != nil {
		return x.Start
	}
	return nil
}

func (x *TimeWindow) GetEnd() *durationpb.Duration {
	if x != nil {
		return x.End
	}
	return nil
}

// ScheduleTasksResponse contains scheduling results.
type ScheduleTasksResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Results            []*ScheduleResult      `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	TotalScheduled     int32                  `protobuf:"varint,2,opt,name=total_scheduled,json=totalScheduled,proto3" json:"total_scheduled,omitempty"`
	UtilizationPercent float64                `protobuf:"fixed64,3,opt,name=utilization_percent,json=utilizationPercent,proto3" json:"utilization_percent,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ScheduleTasksResponse) Reset() {
	*x = ScheduleTasksResponse{}
	mi := &file_internal_engine_grpc_proto_scheduler_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScheduleTasksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScheduleTasksResponse) ProtoMessage() {}

func (x *ScheduleTasksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_engine_grpc_proto_scheduler_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScheduleTasksResponse.ProtoReflect.Descriptor instead.
func (*ScheduleTasksResponse) Descriptor() ([]byte, []int) {
	return file_internal_engine_grpc_proto_scheduler_proto_rawDescGZIP(), []int{6}
}

func (x *ScheduleTasksResponse) GetResults() []*ScheduleResult {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *ScheduleTasksResponse) GetTotalScheduled() int32 {
	if x != nil {
		return x.TotalScheduled
	}
	return 0
}

func (x *ScheduleTasksResponse) GetUtilizationPercent() float64 {
	if x != nil {
		return x.UtilizationPercent
	}
	return 0
}

// ScheduleResult represents the result of scheduling a task.
type ScheduleResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	BlockId       string                 `protobuf:"bytes,2,opt,name=block_id,json=blockId,proto3" json:"block_id,omitempty"`
	StartTime     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	Scheduled     bool                   `protobuf:"varint,5,opt,name=scheduled,proto3" json:"scheduled,omitempty"`
	Reason        string                 `protobuf:"bytes,6,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScheduleResult) Reset() {
	*x = ScheduleResult{}
	mi := &file_internal_engine_grpc_proto_scheduler_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScheduleResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScheduleResult) ProtoMessage() {}

func (x *ScheduleResult) ProtoReflect() protoreflect.Message {
	mi := &file_internal_engine_grpc_proto_scheduler_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScheduleResult.ProtoReflect.Descriptor instead.
func (*ScheduleResult) Descriptor() ([]byte, []int) {
	return file_internal_engine_grpc_proto_scheduler_proto_rawDescGZIP(), []int{7}
}

func (x *ScheduleResult) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *ScheduleResult) GetBlockId() string {
	if x != nil {
		return x.BlockId
	}
	return ""
}

func (x *ScheduleResult) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *ScheduleResult) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

func (x *ScheduleResult) GetScheduled() bool {
	if x != nil {
		return x.Scheduled
	}
	return false
}

func (x *ScheduleResult) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// FindSlotRequest contains parameters for finding a slot.
type FindSlotRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Context        *ExecutionContext      `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	Date           *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"`
	Duration       *durationpb.Duration   `protobuf:"bytes,3,opt,name=duration,proto3" json:"duration,omitempty"`
	PreferredStart *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=preferred_start,json=preferredStart,proto3" json:"preferred_start,omitempty"`
	ExistingBlocks []*ExistingBlock       `protobuf:"bytes,5,rep,name=existing_blocks,json=existingBlocks,proto3" json:"existing_blocks,omitempty"`
	WorkingHours   *WorkingHours          `protobuf:"bytes,6,opt,name=working_hours,json=workingHours,proto3" json:"working_hours,omitempty"`
	Priority       int32                  `protobuf:"varint,7,opt,name=priority,proto3" json:"priority,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *FindSlotRequest) Reset() {
	*x = FindSlotRequest{}
	mi := &file_internal_engine_grpc_proto_scheduler_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindSlotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindSlotRequest) ProtoMessage() {}

func (x *FindSlotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_engine_grpc_proto_scheduler_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindSlotRequest.ProtoReflect.Descriptor instead.
func (*FindSlotRequest) Descriptor() ([]byte, []int) {
	return file_internal_engine_grpc_proto_scheduler_proto_rawDescGZIP(), []int{8}
}

func (x *FindSlotRequest) GetContext() *ExecutionContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *FindSlotRequest) GetDate() *timestamppb.Timestamp {
	if x != nil {
		return x.Date
	}
	return nil
}

func (x *FindSlotRequest) GetDuration() *durationpb.Duration {
	if x != nil {
		return x.Duration
	}
	return nil
}

func (x *FindSlotRequest) GetPreferredStart() *timestamppb.Timestamp {
	if x != nil {
		return x.PreferredStart
	}
	return nil
}

func (x *FindSlotRequest) GetExistingBlocks() []*ExistingBlock {
	if x != nil {
		return x.ExistingBlocks
	}
	return nil
}

func (x *FindSlotRequest) GetWorkingHours() *WorkingHours {
	if x != nil {
		return x.WorkingHours
	}
	return nil
}

func (x *FindSlotRequest) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

// FindSlotResponse contains the found slot.
type FindSlotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slot          *TimeSlot              `protobuf:"bytes,1,opt,name=slot,proto3" json:"slot,omitempty"`
	Found         bool                   `protobuf:"varint,2,opt,name=found,proto3" json:"found,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindSlotResponse) Reset() {
	*x = FindSlotResponse{}
	mi := &file_internal_engine_grpc_proto_scheduler_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindSlotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindSlotResponse) ProtoMessage() {}

func (x *FindSlotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_engine_grpc_proto_scheduler_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindSlotResponse.ProtoReflect.Descriptor instead.
func (*FindSlotResponse) Descriptor() ([]byte, []int) {
	return file_internal_engine_grpc_proto_scheduler_proto_rawDescGZIP(), []int{9}
}

func (x *FindSlotResponse) GetSlot() *TimeSlot {
	if x != nil {
		return x.Slot
	}
	return nil
}

func (x *FindSlotResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *FindSlotResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// TimeSlot represents an available time slot.
type TimeSlot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Start         *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=start,proto3" json:"start,omitempty"`
	End           *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=end,proto3" json:"end,omitempty"`
	Score         float64                `protobuf:"fixed64,3,opt,name=score,proto3" json:"score,omitempty"`
	Reason        string                 `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimeSlot) Reset() {
	*x = TimeSlot{}
	mi := &file_internal_engine_grpc_proto_scheduler_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimeSlot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeSlot) ProtoMessage() {}

func (x *TimeSlot) ProtoReflect() protoreflect.Message {
	mi := &file_internal_engine_grpc_proto_scheduler_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeSlot.ProtoReflect.Descriptor instead.
func (*TimeSlot) Descriptor() ([]byte, []int) {
	return file_internal_engine_grpc_proto_scheduler_proto_rawDescGZIP(), []int{10}
}

func (x *TimeSlot) GetStart() *timestamppb.Timestamp {
	if x != nil {
		return x.Start
	}
	return nil
}

func (x *TimeSlot) GetEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.End
	}
	return nil
}

func (x *TimeSlot) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *TimeSlot) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// RescheduleRequest contains parameters for conflict resolution.
type RescheduleRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Context        *ExecutionContext      `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	Date           *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"`
	NewBlock       *ExistingBlock         `protobuf:"bytes,3,opt,name=new_block,json=newBlock,proto3" json:"new_block,omitempty"`
	ExistingBlocks []*ExistingBlock       `protobuf:"bytes,4,rep,name=existing_blocks,json=existingBlocks,proto3" json:"existing_blocks,omitempty"`
	WorkingHours   *WorkingHours          `protobuf:"bytes,5,opt,name=working_hours,json=workingHours,proto3" json:"working_hours,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RescheduleRequest) Reset() {
	*x = RescheduleRequest{}
	mi := &file_internal_engine_grpc_proto_scheduler_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RescheduleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RescheduleRequest) ProtoMessage() {}

func (x *RescheduleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_engine_grpc_proto_scheduler_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RescheduleRequest.ProtoReflect.Descriptor instead.
func (*RescheduleRequest) Descriptor() ([]byte, []int) {
	return file_internal_engine_grpc_proto_scheduler_proto_rawDescGZIP(), []int{11}
}

func (x *RescheduleRequest) GetContext() *ExecutionContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *RescheduleRequest) GetDate() *timestamppb.Timestamp {
	if x != nil {
		return x.Date
	}
	return nil
}

func (x *RescheduleRequest) GetNewBlock() *ExistingBlock {
	if x != nil {
		return x.NewBlock
	}
	return nil
}

func (x *RescheduleRequest) GetExistingBlocks() []*ExistingBlock {
	if x != nil {
		return x.ExistingBlocks
	}
	return nil
}

func (x *RescheduleRequest) GetWorkingHours() *WorkingHours {
	if x != nil {
		return x.WorkingHours
	}
	return nil
}

// RescheduleResponse contains conflict resolution results.
type RescheduleResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Results             []*ScheduleResult      `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	ConflictsResolved   int32                  `protobuf:"varint,2,opt,name=conflicts_resolved,json=conflictsResolved,proto3" json:"conflicts_resolved,omitempty"`
	UnresolvedConflicts []string               `protobuf:"bytes,3,rep,name=unresolved_conflicts,json=unresolvedConflicts,proto3" json:"unresolved_conflicts,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *RescheduleResponse) Reset() {
	*x = RescheduleResponse{}
	mi := &file_internal_engine_grpc_proto_scheduler_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RescheduleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RescheduleResponse) ProtoMessage() {}

func (x *RescheduleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_engine_grpc_proto_scheduler_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RescheduleResponse.ProtoReflect.Descriptor instead.
func (*RescheduleResponse) Descriptor() ([]byte, []int) {
	return file_internal_engine_grpc_proto_scheduler_proto_rawDescGZIP(), []int{12}
}

func (x *RescheduleResponse) GetResults() []*ScheduleResult {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *RescheduleResponse) GetConflictsResolved() int32 {
	if x != nil {
		return x.ConflictsResolved
	}
	return 0
}

func (x *RescheduleResponse) GetUnresolvedConflicts() []string {
	if x != nil {
		return x.UnresolvedConflicts
	}
	return nil
}

// UtilizationRequest contains parameters for utilization calculation.
type UtilizationRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Context        *ExecutionContext      `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	Date           *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"`
	ExistingBlocks []*ExistingBlock       `protobuf:"bytes,3,rep,name=existing_blocks,json=existingBlocks,proto3" json:"existing_blocks,omitempty"`
	WorkingHours   *WorkingHours          `protobuf:"bytes,4,opt,name=working_hours,json=workingHours,proto3" json:"working_hours,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UtilizationRequest) Reset() {
	*x = UtilizationRequest{}
	mi := &file_internal_engine_grpc_proto_scheduler_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UtilizationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UtilizationRequest) ProtoMessage() {}

func (x *UtilizationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_engine_grpc_proto_scheduler_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UtilizationRequest.ProtoReflect.Descriptor instead.
func (*UtilizationRequest) Descriptor() ([]byte, []int) {
	return file_internal_engine_grpc_proto_scheduler_proto_rawDescGZIP(), []int{13}
}

func (x *UtilizationRequest) GetContext() *ExecutionContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *UtilizationRequest) GetDate() *timestamppb.Timestamp {
	if x != nil {
		return x.Date
	}
	return nil
}

func (x *UtilizationRequest) GetExistingBlocks() []*ExistingBlock {
	if x != nil {
		return x.ExistingBlocks
	}
	return nil
}

func (x *UtilizationRequest) GetWorkingHours() *WorkingHours {
	if x != nil {
		return x.WorkingHours
	}
	return nil
}

// UtilizationResponse contains utilization results.
type UtilizationResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Percent        float64                `protobuf:"fixed64,1,opt,name=percent,proto3" json:"percent,omitempty"`
	TotalAvailable *durationpb.Duration   `protobuf:"bytes,2,opt,name=total_available,json=totalAvailable,proto3" json:"total_available,omitempty"`
	TotalScheduled *durationpb.Duration   `protobuf:"bytes,3,opt,name=total_scheduled,json=totalScheduled,proto3" json:"total_scheduled,omitempty"`
	ByBlockType    map[string]int64       `protobuf:"bytes,4,rep,name=by_block_type,json=byBlockType,proto3" json:"by_block_type,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"` // Duration in nanoseconds
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UtilizationResponse) Reset() {
	*x = UtilizationResponse{}
	mi := &file_internal_engine_grpc_proto_scheduler_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UtilizationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UtilizationResponse) ProtoMessage() {}

func (x *UtilizationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_engine_grpc_proto_scheduler_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UtilizationResponse.ProtoReflect.Descriptor instead.
func (*UtilizationResponse) Descriptor() ([]byte, []int) {
	return file_internal_engine_grpc_proto_scheduler_proto_rawDescGZIP(), []int{14}
}

func (x *UtilizationResponse) GetPercent() float64 {
	if x != nil {
		return x.Percent
	}
	return 0
}

func (x *UtilizationResponse) GetTotalAvailable() *durationpb.Duration {
	if x != nil {
		return x.TotalAvailable
	}
	return nil
}

func (x *UtilizationResponse) GetTotalScheduled() *durationpb.Duration {
	if x != nil {
		return x.TotalScheduled
	}
	return nil
}

func (x *UtilizationResponse) GetByBlockType() map[string]int64 {
	if x != nil {
		return x.ByBlockType
	}
	return nil
}

var File_internal_engine_grpc_proto_scheduler_proto protoreflect.FileDescriptor

const file_internal_engine_grpc_proto_scheduler_proto_rawDesc = "" +
	"\n" +
	"*internal/engine/grpc/proto/scheduler.proto\x12\x10orbita.engine.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/duration.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a'internal/engine/grpc/proto/engine.proto\"\xcc\x02\n" +
	"\x14ScheduleTasksRequest\x12<\n" +
	"\acontext\x18\x01 \x01(\v2\".orbita.engine.v1.ExecutionContextR\acontext\x12.\n" +
	"\x04date\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x04date\x127\n" +
	"\x05tasks\x18\x03 \x03(\v2!.orbita.engine.v1.SchedulableTaskR\x05tasks\x12H\n" +
	"\x0fexisting_blocks\x18\x04 \x03(\v2\x1f.orbita.engine.v1.ExistingBlockR\x0eexistingBlocks\x12C\n" +
	"\rworking_hours\x18\x05 \x01(\v2\x1e.orbita.engine.v1.WorkingHoursR\fworkingHours\"\xd5\x02\n" +
	"\x0fSchedulableTask\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x1a\n" +
	"\bpriority\x18\x03 \x01(\x05R\bpriority\x125\n" +
	"\bduration\x18\x04 \x01(\v2\x19.google.protobuf.DurationR\bduration\x125\n" +
	"\bdue_date\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\adueDate\x12\x1d\n" +
	"\n" +
	"block_type\x18\x06 \x01(\tR\tblockType\x12>\n" +
	"\vconstraints\x18\a \x03(\v2\x1c.orbita.engine.v1.ConstraintR\vconstraints\x123\n" +
	"\bmetadata\x18\b \x01(\v2\x17.google.protobuf.StructR\bmetadata\"\xbf\x01\n" +
	"\n" +
	"Constraint\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x120\n" +
	"\x05start\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x05start\x12,\n" +
	"\x03end\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x03end\x12!\n" +
	"\freference_id\x18\x04 \x01(\tR\vreferenceId\x12\x1a\n" +
	"\bflexible\x18\x05 \x01(\bR\bflexible\"\xc7\x01\n" +
	"\rExistingBlock\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x120\n" +
	"\x05start\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x05start\x12,\n" +
	"\x03end\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x03end\x12\x14\n" +
	"\x05title\x18\x05 \x01(\tR\x05title\x12\x1c\n" +
	"\timmovable\x18\x06 \x01(\bR\timmovable\"\xa2\x01\n" +
	"\fWorkingHours\x12/\n" +
	"\x05start\x18\x01 \x01(\v2\x19.google.protobuf.DurationR\x05start\x12+\n" +
	"\x03end\x18\x02 \x01(\v2\x19.google.protobuf.DurationR\x03end\x124\n" +
	"\x06breaks\x18\x03 \x03(\v2\x1c.orbita.engine.v1.TimeWindowR\x06breaks\"j\n" +
	"\n" +
	"TimeWindow\x12/\n" +
	"\x05start\x18\x01 \x01(\v2\x19.google.protobuf.DurationR\x05start\x12+\n" +
	"\x03end\x18\x02 \x01(\v2\x19.google.protobuf.DurationR\x03end\"\xad\x01\n" +
	"\x15ScheduleTasksResponse\x12:\n" +
	"\aresults\x18\x01 \x03(\v2 .orbita.engine.v1.ScheduleResultR\aresults\x12'\n" +
	"\x0ftotal_scheduled\x18\x02 \x01(\x05R\x0etotalScheduled\x12/\n" +
	"\x13utilization_percent\x18\x03 \x01(\x01R\x12utilizationPercent\"\xec\x01\n" +
	"\x0eScheduleResult\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x19\n" +
	"\bblock_id\x18\x02 \x01(\tR\ablockId\x129\n" +
	"\n" +
	"start_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\x12\x1c\n" +
	"\tscheduled\x18\x05 \x01(\bR\tscheduled\x12\x16\n" +
	"\x06reason\x18\x06 \x01(\tR\x06reason\"\xa6\x03\n" +
	"\x0fFindSlotRequest\x12<\n" +
	"\acontext\x18\x01 \x01(\v2\".orbita.engine.v1.ExecutionContextR\acontext\x12.\n" +
	"\x04date\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x04date\x125\n" +
	"\bduration\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\bduration\x12C\n" +
	"\x0fpreferred_start\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x0epreferredStart\x12H\n" +
	"\x0fexisting_blocks\x18\x05 \x03(\v2\x1f.orbita.engine.v1.ExistingBlockR\x0eexistingBlocks\x12C\n" +
	"\rworking_hours\x18\x06 \x01(\v2\x1e.orbita.engine.v1.WorkingHoursR\fworkingHours\x12\x1a\n" +
	"\bpriority\x18\a \x01(\x05R\bpriority\"n\n" +
	"\x10FindSlotResponse\x12.\n" +
	"\x04slot\x18\x01 \x01(\v2\x1a.orbita.engine.v1.TimeSlotR\x04slot\x12\x14\n" +
	"\x05found\x18\x02 \x01(\bR\x05found\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"\x98\x01\n" +
	"\bTimeSlot\x120\n" +
	"\x05start\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x05start\x12,\n" +
	"\x03end\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x03end\x12\x14\n" +
	"\x05score\x18\x03 \x01(\x01R\x05score\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\"\xce\x02\n" +
	"\x11RescheduleRequest\x12<\n" +
	"\acontext\x18\x01 \x01(\v2\".orbita.engine.v1.ExecutionContextR\acontext\x12.\n" +
	"\x04date\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x04date\x12<\n" +
	"\tnew_block\x18\x03 \x01(\v2\x1f.orbita.engine.v1.ExistingBlockR\bnewBlock\x12H\n" +
	"\x0fexisting_blocks\x18\x04 \x03(\v2\x1f.orbita.engine.v1.ExistingBlockR\x0eexistingBlocks\x12C\n" +
	"\rworking_hours\x18\x05 \x01(\v2\x1e.orbita.engine.v1.WorkingHoursR\fworkingHours\"\xb2\x01\n" +
	"\x12RescheduleResponse\x12:\n" +
	"\aresults\x18\x01 \x03(\v2 .orbita.engine.v1.ScheduleResultR\aresults\x12-\n" +
	"\x12conflicts_resolved\x18\x02 \x01(\x05R\x11conflictsResolved\x121\n" +
	"\x14unresolved_conflicts\x18\x03 \x03(\tR\x13unresolvedConflicts\"\x91\x02\n" +
	"\x12UtilizationRequest\x12<\n" +
	"\acontext\x18\x01 \x01(\v2\".orbita.engine.v1.ExecutionContextR\acontext\x12.\n" +
	"\x04date\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x04date\x12H\n" +
	"\x0fexisting_blocks\x18\x03 \x03(\v2\x1f.orbita.engine.v1.ExistingBlockR\x0eexistingBlocks\x12C\n" +
	"\rworking_hours\x18\x04 \x01(\v2\x1e.orbita.engine.v1.WorkingHoursR\fworkingHours\"\xd3\x02\n" +
	"\x13UtilizationResponse\x12\x18\n" +
	"\apercent\x18\x01 \x01(\x01R\apercent\x12B\n" +
	"\x0ftotal_available\x18\x02 \x01(\v2\x19.google.protobuf.DurationR\x0etotalAvailable\x12B\n" +
	"\x0ftotal_scheduled\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\x0etotalScheduled\x12Z\n" +
	"\rby_block_type\x18\x04 \x03(\v26.orbita.engine.v1.UtilizationResponse.ByBlockTypeEntryR\vbyBlockType\x1a>\n" +
	"\x10ByBlockTypeEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x012\x94\x03\n" +
	"\x0fSchedulerEngine\x12`\n" +
	"\rScheduleTasks\x12&.orbita.engine.v1.ScheduleTasksRequest\x1a'.orbita.engine.v1.ScheduleTasksResponse\x12X\n" +
	"\x0fFindOptimalSlot\x12!.orbita.engine.v1.FindSlotRequest\x1a\".orbita.engine.v1.FindSlotResponse\x12`\n" +
	"\x13RescheduleConflicts\x12#.orbita.engine.v1.RescheduleRequest\x1a$.orbita.engine.v1.RescheduleResponse\x12c\n" +
	"\x14CalculateUtilization\x12$.orbita.engine.v1.UtilizationRequest\x1a%.orbita.engine.v1.UtilizationResponseBEZCgithub.com/felixgeelhaar/orbita/internal/engine/grpc/proto;enginepbb\x06proto3"

var (
	file_internal_engine_grpc_proto_scheduler_proto_rawDescOnce sync.Once
	file_internal_engine_grpc_proto_scheduler_proto_rawDescData []byte
)

func file_internal_engine_grpc_proto_scheduler_proto_rawDescGZIP() []byte {
	file_internal_engine_grpc_proto_scheduler_proto_rawDescOnce.Do(func() {
		file_internal_engine_grpc_proto_scheduler_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_engine_grpc_proto_scheduler_proto_rawDesc), len(file_internal_engine_grpc_proto_scheduler_proto_rawDesc)))
	})
	return file_internal_engine_grpc_proto_scheduler_proto_rawDescData
}

var file_internal_engine_grpc_proto_scheduler_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_internal_engine_grpc_proto_scheduler_proto_goTypes = []any{
	(*ScheduleTasksRequest)(nil),  // 0: orbita.engine.v1.ScheduleTasksRequest
	(*SchedulableTask)(nil),       // 1: orbita.engine.v1.SchedulableTask
	(*Constraint)(nil),            // 2: orbita.engine.v1.Constraint
	(*ExistingBlock)(nil),         // 3: orbita.engine.v1.ExistingBlock
	(*WorkingHours)(nil),          // 4: orbita.engine.v1.WorkingHours
	(*TimeWindow)(nil),            // 5: orbita.engine.v1.TimeWindow
	(*ScheduleTasksResponse)(nil), // 6: orbita.engine.v1.ScheduleTasksResponse
	(*ScheduleResult)(nil),        // 7: orbita.engine.v1.ScheduleResult
	(*FindSlotRequest)(nil),       // 8: orbita.engine.v1.FindSlotRequest
	(*FindSlotResponse)(nil),      // 9: orbita.engine.v1.FindSlotResponse
	(*TimeSlot)(nil),              // 10: orbita.engine.v1.TimeSlot
	(*RescheduleRequest)(nil),     // 11: orbita.engine.v1.RescheduleRequest
	(*RescheduleResponse)(nil),    // 12: orbita.engine.v1.RescheduleResponse
	(*UtilizationRequest)(nil),    // 13: orbita.engine.v1.UtilizationRequest
	(*UtilizationResponse)(nil),   // 14: orbita.engine.v1.UtilizationResponse
	nil,                           // 15: orbita.engine.v1.UtilizationResponse.ByBlockTypeEntry
	(*ExecutionContext)(nil),      // 16: orbita.engine.v1.ExecutionContext
	(*timestamppb.Timestamp)(nil), // 17: google.protobuf.Timestamp
	(*durationpb.Duration)(nil),   // 18: google.protobuf.Duration
	(*structpb.Struct)(nil),       // 19: google.protobuf.Struct
}
var file_internal_engine_grpc_proto_scheduler_proto_depIdxs = []int32{
	16, // 0: orbita.engine.v1.ScheduleTasksRequest.context:type_name -> orbita.engine.v1.ExecutionContext
	17, // 1: orbita.engine.v1.ScheduleTasksRequest.date:type_name -> google.protobuf.Timestamp
	1,  // 2: orbita.engine.v1.ScheduleTasksRequest.tasks:type_name -> orbita.engine.v1.SchedulableTask
	3,  // 3: orbita.engine.v1.ScheduleTasksRequest.existing_blocks:type_name -> orbita.engine.v1.ExistingBlock
	4,  // 4: orbita.engine.v1.ScheduleTasksRequest.working_hours:type_name -> orbita.engine.v1.WorkingHours
	18, // 5: orbita.engine.v1.SchedulableTask.duration:type_name -> google.protobuf.Duration
	17, // 6: orbita.engine.v1.SchedulableTask.due_date:type_name -> google.protobuf.Timestamp
	2,  // 7: orbita.engine.v1.SchedulableTask.constraints:type_name -> orbita.engine.v1.Constraint
	19, // 8: orbita.engine.v1.SchedulableTask.metadata:type_name -> google.protobuf.Struct
	17, // 9: orbita.engine.v1.Constraint.start:type_name -> google.protobuf.Timestamp
	17, // 10: orbita.engine.v1.Constraint.end:type_name -> google.protobuf.Timestamp
	17, // 11: orbita.engine.v1.ExistingBlock.start:type_name -> google.protobuf.Timestamp
	17, // 12: orbita.engine.v1.ExistingBlock.end:type_name -> google.protobuf.Timestamp
	18, // 13: orbita.engine.v1.WorkingHours.start:type_name -> google.protobuf.Duration
	18, // 14: orbita.engine.v1.WorkingHours.end:type_name -> google.protobuf.Duration
	5,  // 15: orbita.engine.v1.WorkingHours.breaks:type_name -> orbita.engine.v1.TimeWindow
	18, // 16: orbita.engine.v1.TimeWindow.start:type_name -> google.protobuf.Duration
	18, // 17: orbita.engine.v1.TimeWindow.end:type_name -> google.protobuf.Duration
	7,  // 18: orbita.engine.v1.ScheduleTasksResponse.results:type_name -> orbita.engine.v1.ScheduleResult
	17, // 19: orbita.engine.v1.ScheduleResult.start_time:type_name -> google.protobuf.Timestamp
	17, // 20: orbita.engine.v1.ScheduleResult.end_time:type_name -> google.protobuf.Timestamp
	16, // 21: orbita.engine.v1.FindSlotRequest.context:type_name -> orbita.engine.v1.ExecutionContext
	17, // 22: orbita.engine.v1.FindSlotRequest.date:type_name -> google.protobuf.Timestamp
	18, // 23: orbita.engine.v1.FindSlotRequest.duration:type_name -> google.protobuf.Duration
	17, // 24: orbita.engine.v1.FindSlotRequest.preferred_start:type_name -> google.protobuf.Timestamp
	3,  // 25: orbita.engine.v1.FindSlotRequest.existing_blocks:type_name -> orbita.engine.v1.ExistingBlock
	4,  // 26: orbita.engine.v1.FindSlotRequest.working_hours:type_name -> orbita.engine.v1.WorkingHours
	10, // 27: orbita.engine.v1.FindSlotResponse.slot:type_name -> orbita.engine.v1.TimeSlot
	17, // 28: orbita.engine.v1.TimeSlot.start:type_name -> google.protobuf.Timestamp
	17, // 29: orbita.engine.v1.TimeSlot.end:type_name -> google.protobuf.Timestamp
	16, // 30: orbita.engine.v1.RescheduleRequest.context:type_name -> orbita.engine.v1.ExecutionContext
	17, // 31: orbita.engine.v1.RescheduleRequest.date:type_name -> google.protobuf.Timestamp
	3,  // 32: orbita.engine.v1.RescheduleRequest.new_block:type_name -> orbita.engine.v1.ExistingBlock
	3,  // 33: orbita.engine.v1.RescheduleRequest.existing_blocks:type_name -> orbita.engine.v1.ExistingBlock
	4,  // 34: orbita.engine.v1.RescheduleRequest.working_hours:type_name -> orbita.engine.v1.WorkingHours
	7,  // 35: orbita.engine.v1.RescheduleResponse.results:type_name -> orbita.engine.v1.ScheduleResult
	16, // 36: orbita.engine.v1.UtilizationRequest.context:type_name -> orbita.engine.v1.ExecutionContext
	17, // 37: orbita.engine.v1.UtilizationRequest.date:type_name -> google.protobuf.Timestamp
	3,  // 38: orbita.engine.v1.UtilizationRequest.existing_blocks:type_name -> orbita.engine.v1.ExistingBlock
	4,  // 39: orbita.engine.v1.UtilizationRequest.working_hours:type_name -> orbita.engine.v1.WorkingHours
	18, // 40: orbita.engine.v1.UtilizationResponse.total_available:type_name -> google.protobuf.Duration
	18, // 41: orbita.engine.v1.UtilizationResponse.total_scheduled:type_name -> google.protobuf.Duration
	15, // 42: orbita.engine.v1.UtilizationResponse.by_block_type:type_name -> orbita.engine.v1.UtilizationResponse.ByBlockTypeEntry
	0,  // 43: orbita.engine.v1.SchedulerEngine.ScheduleTasks:input_type -> orbita.engine.v1.ScheduleTasksRequest
	8,  // 44: orbita.engine.v1.SchedulerEngine.FindOptimalSlot:input_type -> orbita.engine.v1.FindSlotRequest
	11, // 45: orbita.engine.v1.SchedulerEngine.RescheduleConflicts:input_type -> orbita.engine.v1.RescheduleRequest
	13, // 46: orbita.engine.v1.SchedulerEngine.CalculateUtilization:input_type -> orbita.engine.v1.UtilizationRequest
	6,  // 47: orbita.engine.v1.SchedulerEngine.ScheduleTasks:output_type -> orbita.engine.v1.ScheduleTasksResponse
	9,  // 48: orbita.engine.v1.SchedulerEngine.FindOptimalSlot:output_type -> orbita.engine.v1.FindSlotResponse
	12, // 49: orbita.engine.v1.SchedulerEngine.RescheduleConflicts:output_type -> orbita.engine.v1.RescheduleResponse
	14, // 50: orbita.engine.v1.SchedulerEngine.CalculateUtilization:output_type -> orbita.engine.v1.UtilizationResponse
	47, // [47:51] is the sub-list for method output_type
	43, // [43:47] is the sub-list for method input_type
	43, // [43:43] is the sub-list for extension type_name
	43, // [43:43] is the sub-list for extension extendee
	0,  // [0:43] is the sub-list for field type_name
}

func init() { file_internal_engine_grpc_proto_scheduler_proto_init() }
func file_internal_engine_grpc_proto_scheduler_proto_init() {
	if File_internal_engine_grpc_proto_scheduler_proto != nil {
		return
	}
	file_internal_engine_grpc_proto_engine_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_engine_grpc_proto_scheduler_proto_rawDesc), len(file_internal_engine_grpc_proto_scheduler_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_engine_grpc_proto_scheduler_proto_goTypes,
		DependencyIndexes: file_internal_engine_grpc_proto_scheduler_proto_depIdxs,
		MessageInfos:      file_internal_engine_grpc_proto_scheduler_proto_msgTypes,
	}.Build()
	File_internal_engine_grpc_proto_scheduler_proto = out.File
	file_internal_engine_grpc_proto_scheduler_proto_goTypes = nil
	file_internal_engine_grpc_proto_scheduler_proto_depIdxs = nil
}
