// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: internal/engine/grpc/proto/scheduler.proto

package enginepb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SchedulerEngine_ScheduleTasks_FullMethodName        = "/orbita.engine.v1.SchedulerEngine/ScheduleTasks"
	SchedulerEngine_FindOptimalSlot_FullMethodName      = "/orbita.engine.v1.SchedulerEngine/FindOptimalSlot"
	SchedulerEngine_RescheduleConflicts_FullMethodName  = "/orbita.engine.v1.SchedulerEngine/RescheduleConflicts"
	SchedulerEngine_CalculateUtilization_FullMethodName = "/orbita.engine.v1.SchedulerEngine/CalculateUtilization"
)

// SchedulerEngineClient is the client API for SchedulerEngine service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SchedulerEngine provides scheduling capabilities.
type SchedulerEngineClient interface {
	// ScheduleTasks schedules multiple tasks into time blocks.
	ScheduleTasks(ctx context.Context, in *ScheduleTasksRequest, opts ...grpc.CallOption) (*ScheduleTasksResponse, error)
	// FindOptimalSlot finds the best available time slot.
	FindOptimalSlot(ctx context.Context, in *FindSlotRequest, opts ...grpc.CallOption) (*FindSlotResponse, error)
	// RescheduleConflicts handles rescheduling when conflicts arise.
	RescheduleConflicts(ctx context.Context, in *RescheduleRequest, opts ...grpc.CallOption) (*RescheduleResponse, error)
	// CalculateUtilization calculates schedule utilization.
	CalculateUtilization(ctx context.Context, in *UtilizationRequest, opts ...grpc.CallOption) (*UtilizationResponse, error)
}

type schedulerEngineClient struct {
	cc grpc.ClientConnInterface
}

func NewSchedulerEngineClient(cc grpc.ClientConnInterface) SchedulerEngineClient {
	return &schedulerEngineClient{cc}
}

func (c *schedulerEngineClient) ScheduleTasks(ctx context.Context, in *ScheduleTasksRequest, opts ...grpc.CallOption) (*ScheduleTasksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ScheduleTasksResponse)
	err := c.cc.Invoke(ctx, SchedulerEngine_ScheduleTasks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schedulerEngineClient) FindOptimalSlot(ctx context.Context, in *FindSlotRequest, opts ...grpc.CallOption) (*FindSlotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FindSlotResponse)
	err := c.cc.Invoke(ctx, SchedulerEngine_FindOptimalSlot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schedulerEngineClient) RescheduleConflicts(ctx context.Context, in *RescheduleRequest, opts ...grpc.CallOption) (*RescheduleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RescheduleResponse)
	err := c.cc.Invoke(ctx, SchedulerEngine_RescheduleConflicts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schedulerEngineClient) CalculateUtilization(ctx context.Context, in *UtilizationRequest, opts ...grpc.CallOption) (*UtilizationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UtilizationResponse)
	err := c.cc.Invoke(ctx, SchedulerEngine_CalculateUtilization_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SchedulerEngineServer is the server API for SchedulerEngine service.
// All implementations must embed UnimplementedSchedulerEngineServer
// for forward compatibility.
//
// SchedulerEngine provides scheduling capabilities.
type SchedulerEngineServer interface {
	// ScheduleTasks schedules multiple tasks into time blocks.
	ScheduleTasks(context.Context, *ScheduleTasksRequest) (*ScheduleTasksResponse, error)
	// FindOptimalSlot finds the best available time slot.
	FindOptimalSlot(context.Context, *FindSlotRequest) (*FindSlotResponse, error)
	// RescheduleConflicts handles rescheduling when conflicts arise.
	RescheduleConflicts(context.Context, *RescheduleRequest) (*RescheduleResponse, error)
	// CalculateUtilization calculates schedule utilization.
	CalculateUtilization(context.Context, *UtilizationRequest) (*UtilizationResponse, error)
	mustEmbedUnimplementedSchedulerEngineServer()
}

// UnimplementedSchedulerEngineServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSchedulerEngineServer struct{}

func (UnimplementedSchedulerEngineServer) ScheduleTasks(context.Context, *ScheduleTasksRequest) (*ScheduleTasksResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ScheduleTasks not implemented")
}
func (UnimplementedSchedulerEngineServer) FindOptimalSlot(context.Context, *FindSlotRequest) (*FindSlotResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FindOptimalSlot not implemented")
}
func (UnimplementedSchedulerEngineServer) RescheduleConflicts(context.Context, *RescheduleRequest) (*RescheduleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RescheduleConflicts not implemented")
}
func (UnimplementedSchedulerEngineServer) CalculateUtilization(context.Context, *UtilizationRequest) (*UtilizationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CalculateUtilization not implemented")
}
func (UnimplementedSchedulerEngineServer) mustEmbedUnimplementedSchedulerEngineServer() {}
func (UnimplementedSchedulerEngineServer) testEmbeddedByValue()                         {}

// UnsafeSchedulerEngineServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SchedulerEngineServer will
// result in compilation errors.
type UnsafeSchedulerEngineServer interface {
	mustEmbedUnimplementedSchedulerEngineServer()
}

func RegisterSchedulerEngineServer(s grpc.ServiceRegistrar, srv SchedulerEngineServer) {
	// If the following call panics, it indicates UnimplementedSchedulerEngineServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SchedulerEngine_ServiceDesc, srv)
}

func _SchedulerEngine_ScheduleTasks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScheduleTasksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchedulerEngineServer).ScheduleTasks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SchedulerEngine_ScheduleTasks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchedulerEngineServer).ScheduleTasks(ctx, req.(*ScheduleTasksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SchedulerEngine_FindOptimalSlot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindSlotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchedulerEngineServer).FindOptimalSlot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SchedulerEngine_FindOptimalSlot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchedulerEngineServer).FindOptimalSlot(ctx, req.(*FindSlotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SchedulerEngine_RescheduleConflicts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RescheduleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchedulerEngineServer).RescheduleConflicts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SchedulerEngine_RescheduleConflicts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchedulerEngineServer).RescheduleConflicts(ctx, req.(*RescheduleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SchedulerEngine_CalculateUtilization_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UtilizationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchedulerEngineServer).CalculateUtilization(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SchedulerEngine_CalculateUtilization_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchedulerEngineServer).CalculateUtilization(ctx, req.(*UtilizationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SchedulerEngine_ServiceDesc is the grpc.ServiceDesc for SchedulerEngine service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SchedulerEngine_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "orbita.engine.v1.SchedulerEngine",
	HandlerType: (*SchedulerEngineServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ScheduleTasks",
			Handler:    _SchedulerEngine_ScheduleTasks_Handler,
		},
		{
			MethodName: "FindOptimalSlot",
			Handler:    _SchedulerEngine_FindOptimalSlot_Handler,
		},
		{
			MethodName: "RescheduleConflicts",
			Handler:    _SchedulerEngine_RescheduleConflicts_Handler,
		},
		{
			MethodName: "CalculateUtilization",
			Handler:    _SchedulerEngine_CalculateUtilization_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/engine/grpc/proto/scheduler.proto",
}
